# Set to true/false to enable/disable this mod.
super_enable = true

# If enabled fixes movies to correct 16:9 ratio.
[movies]
enable = true

# If enabled constrains the HUD to one of the presets:
# 0 - 16:9
# 1 - 21:9
# 2 - 32:9
# other - 16:9
[hud]
enable = false
constrain = 0
