# Set to true/false to enable/disable this mod.
super_enable = true

# If enabled fixes movies to correct 16:9 ratio.
[movies]
enable = true

# If enabled constrains the HUD to one of the presets:
# 0 - 16:9
# 1 - 21:9
# 2 - 32:9
# other - 16:9
[hud]
enable = false
constrain = 0

# By default the game has all these post processing
# effects on and active.
[post_processing]
motion_blur = true
depth_of_field = true
bloom = true
film_grain = true
chromatic_aberration = true
vignette = true

# If enabled replaces the default game font with your custom font.
# `file` takes both relative paths from the `scripts` folder this
# config toml resides in and also absolute paths.
# Example relative: file = "fonts/MyFont.ttf"
# Example absolute: file = 'C:\Some\Absolute\Path\To\MyFont.ttf'
[fonts]
enable = false
file = ""
