#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BtlUnitAI_661Adhafera1

#include "Basic.hpp"

#include "BP_BtlUnitAI_classes.hpp"
#include "mucha_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_BtlUnitAI_661Adhafera1.BP_BtlUnitAI_661Adhafera1_C
// 0x0058 (0x00D8 - 0x0080)
class UBP_BtlUnitAI_661Adhafera1_C final : public UBP_BtlUnitAI_C
{
public:
	bool                                          第二形態変化フラグ;                                // 0x007D(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          開幕フラグ;                                        // 0x007E(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          力溜め;                                            // 0x007F(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        DMGP;                                              // 0x0080(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         行動数;                                            // 0x0088(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Threeターン毎;                                     // 0x008C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        割合50;                                            // 0x0090(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          初回雄叫びフラグ;                                  // 0x0098(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_99[0x3];                                       // 0x0099(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         雄叫びID;                                          // 0x009C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         力溜め行動数;                                      // 0x00A0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A4[0x4];                                       // 0x00A4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        BreakPN;                                           // 0x00A8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        割合25;                                            // 0x00B0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        割合15;                                            // 0x00B8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         ターン内行動数;                                    // 0x00C0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         被ダメカウント;                                    // 0x00C4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         補正カウント;                                      // 0x00C8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         怨嗟の声使用カウント;                              // 0x00CC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         快復使用カウント;                                  // 0x00D0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          使用フラグ;                                        // 0x00D4(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	int32 ExecuteBreakRecoveryInner();
	int32 ExecuteInner();
	int32 ExecuteRecieveDamageInner(class ACPP_BtlUnit* pAttacker, const int32 SkillId, const EeResistance resistance, const EeSkillDamageType DamageType);
	int32 ExecuteSkillActionEndInner();
	int32 ThinkInner();
	bool 無属性判定();
	void 被ダメ補正();
	void 被ダメ補正緩和();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_BtlUnitAI_661Adhafera1_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_BtlUnitAI_661Adhafera1_C")
	}
	static class UBP_BtlUnitAI_661Adhafera1_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_BtlUnitAI_661Adhafera1_C>();
	}
};
DUMPER7_ASSERTS_UBP_BtlUnitAI_661Adhafera1_C;

SDK_NAMESPACE_END
