#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BtlUnitAI_423Sol

#include "Basic.hpp"

#include "BP_BtlUnitAI_423Sol_classes.hpp"
#include "BP_BtlUnitAI_423Sol_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_BtlUnitAI_423Sol.BP_BtlUnitAI_423Sol_C.ExecuteInner
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

int32 UBP_BtlUnitAI_423Sol_C::ExecuteInner()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlUnitAI_423Sol_C", "ExecuteInner");

	Params::BP_BtlUnitAI_423Sol_C_ExecuteInner Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_BtlUnitAI_423Sol.BP_BtlUnitAI_423Sol_C.ThinkInner
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

int32 UBP_BtlUnitAI_423Sol_C::ThinkInner()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlUnitAI_423Sol_C", "ThinkInner");

	Params::BP_BtlUnitAI_423Sol_C_ThinkInner Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_BtlUnitAI_423Sol.BP_BtlUnitAI_423Sol_C.リセットオーラ
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   reset_exec                                             (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_BtlUnitAI_423Sol_C::リセットオーラ(bool* reset_exec)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlUnitAI_423Sol_C", "リセットオーラ");

	Params::BP_BtlUnitAI_423Sol_C_リセットオーラ Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (reset_exec != nullptr)
		*reset_exec = Parms.reset_exec;
}


// Function BP_BtlUnitAI_423Sol.BP_BtlUnitAI_423Sol_C.攻撃パターン 4
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_BtlUnitAI_423Sol_C::攻撃パターン_4()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlUnitAI_423Sol_C", "攻撃パターン 4");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BtlUnitAI_423Sol.BP_BtlUnitAI_423Sol_C.攻撃パターン3
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_BtlUnitAI_423Sol_C::攻撃パターン3()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlUnitAI_423Sol_C", "攻撃パターン3");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
