#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BtlUnitAI_462Elnath2A

#include "Basic.hpp"

#include "BP_BtlUnitAI_462Elnath2A_classes.hpp"
#include "BP_BtlUnitAI_462Elnath2A_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_BtlUnitAI_462Elnath2A.BP_BtlUnitAI_462Elnath2A_C.ExecuteBeginCounterInner
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

int32 UBP_BtlUnitAI_462Elnath2A_C::ExecuteBeginCounterInner()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlUnitAI_462Elnath2A_C", "ExecuteBeginCounterInner");

	Params::BP_BtlUnitAI_462Elnath2A_C_ExecuteBeginCounterInner Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_BtlUnitAI_462Elnath2A.BP_BtlUnitAI_462Elnath2A_C.ExecuteBreakRecoveryInner
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

int32 UBP_BtlUnitAI_462Elnath2A_C::ExecuteBreakRecoveryInner()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlUnitAI_462Elnath2A_C", "ExecuteBreakRecoveryInner");

	Params::BP_BtlUnitAI_462Elnath2A_C_ExecuteBreakRecoveryInner Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_BtlUnitAI_462Elnath2A.BP_BtlUnitAI_462Elnath2A_C.ExecuteInner
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

int32 UBP_BtlUnitAI_462Elnath2A_C::ExecuteInner()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlUnitAI_462Elnath2A_C", "ExecuteInner");

	Params::BP_BtlUnitAI_462Elnath2A_C_ExecuteInner Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_BtlUnitAI_462Elnath2A.BP_BtlUnitAI_462Elnath2A_C.ExecuteRecieveDamageInner
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ACPP_BtlUnit*                     pAttacker                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const int32                             SkillId                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const EeResistance                      resistance                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const EeSkillDamageType                 DamageType                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

int32 UBP_BtlUnitAI_462Elnath2A_C::ExecuteRecieveDamageInner(class ACPP_BtlUnit* pAttacker, const int32 SkillId, const EeResistance resistance, const EeSkillDamageType DamageType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlUnitAI_462Elnath2A_C", "ExecuteRecieveDamageInner");

	Params::BP_BtlUnitAI_462Elnath2A_C_ExecuteRecieveDamageInner Parms{};

	Parms.pAttacker = pAttacker;
	Parms.SkillId = SkillId;
	Parms.resistance = resistance;
	Parms.DamageType = DamageType;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_BtlUnitAI_462Elnath2A.BP_BtlUnitAI_462Elnath2A_C.ExecuteSkillActionEndInner
// (Event, Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

int32 UBP_BtlUnitAI_462Elnath2A_C::ExecuteSkillActionEndInner()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlUnitAI_462Elnath2A_C", "ExecuteSkillActionEndInner");

	Params::BP_BtlUnitAI_462Elnath2A_C_ExecuteSkillActionEndInner Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_BtlUnitAI_462Elnath2A.BP_BtlUnitAI_462Elnath2A_C.ExecuteUbergraph_BP_BtlUnitAI_462Elnath2A
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_BtlUnitAI_462Elnath2A_C::ExecuteUbergraph_BP_BtlUnitAI_462Elnath2A(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlUnitAI_462Elnath2A_C", "ExecuteUbergraph_BP_BtlUnitAI_462Elnath2A");

	Params::BP_BtlUnitAI_462Elnath2A_C_ExecuteUbergraph_BP_BtlUnitAI_462Elnath2A Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BtlUnitAI_462Elnath2A.BP_BtlUnitAI_462Elnath2A_C.HP減少割合判定
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Cure                                                   (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_BtlUnitAI_462Elnath2A_C::HP減少割合判定(bool* Cure)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlUnitAI_462Elnath2A_C", "HP減少割合判定");

	Params::BP_BtlUnitAI_462Elnath2A_C_HP減少割合判定 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Cure != nullptr)
		*Cure = Parms.Cure;
}


// Function BP_BtlUnitAI_462Elnath2A.BP_BtlUnitAI_462Elnath2A_C.Initialize
// (Event, Public, BlueprintEvent)

void UBP_BtlUnitAI_462Elnath2A_C::Initialize()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlUnitAI_462Elnath2A_C", "Initialize");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BtlUnitAI_462Elnath2A.BP_BtlUnitAI_462Elnath2A_C.ThinkInner
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

int32 UBP_BtlUnitAI_462Elnath2A_C::ThinkInner()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlUnitAI_462Elnath2A_C", "ThinkInner");

	Params::BP_BtlUnitAI_462Elnath2A_C_ThinkInner Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_BtlUnitAI_462Elnath2A.BP_BtlUnitAI_462Elnath2A_C.形態変化HP判定
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   NewParam                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_BtlUnitAI_462Elnath2A_C::形態変化HP判定(bool* NewParam)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlUnitAI_462Elnath2A_C", "形態変化HP判定");

	Params::BP_BtlUnitAI_462Elnath2A_C_形態変化HP判定 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (NewParam != nullptr)
		*NewParam = Parms.NewParam;
}


// Function BP_BtlUnitAI_462Elnath2A.BP_BtlUnitAI_462Elnath2A_C.形態変化フロー
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UBP_BtlUnitAI_462Elnath2A_C::形態変化フロー()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlUnitAI_462Elnath2A_C", "形態変化フロー");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
