#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BtlUnitAI_292Page256

#include "Basic.hpp"

#include "BP_BtlUnitAI_292Page256_classes.hpp"
#include "BP_BtlUnitAI_292Page256_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_BtlUnitAI_292Page256.BP_BtlUnitAI_292Page256_C.ExecuteInner
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

int32 UBP_BtlUnitAI_292Page256_C::ExecuteInner()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlUnitAI_292Page256_C", "ExecuteInner");

	Params::BP_BtlUnitAI_292Page256_C_ExecuteInner Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_BtlUnitAI_292Page256.BP_BtlUnitAI_292Page256_C.ExecuteSkillActionEndInner
// (Event, Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

int32 UBP_BtlUnitAI_292Page256_C::ExecuteSkillActionEndInner()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlUnitAI_292Page256_C", "ExecuteSkillActionEndInner");

	Params::BP_BtlUnitAI_292Page256_C_ExecuteSkillActionEndInner Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_BtlUnitAI_292Page256.BP_BtlUnitAI_292Page256_C.ThinkInner
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

int32 UBP_BtlUnitAI_292Page256_C::ThinkInner()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlUnitAI_292Page256_C", "ThinkInner");

	Params::BP_BtlUnitAI_292Page256_C_ThinkInner Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_BtlUnitAI_292Page256.BP_BtlUnitAI_292Page256_C.行動パターン3
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_BtlUnitAI_292Page256_C::行動パターン3()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlUnitAI_292Page256_C", "行動パターン3");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
