#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BtlUnitAI_20004EvtSuika

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_BtlUnitAI_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_BtlUnitAI_20004EvtSuika.BP_BtlUnitAI_20004EvtSuika_C
// 0x0018 (0x0098 - 0x0080)
class UBP_BtlUnitAI_20004EvtSuika_C final : public UBP_BtlUnitAI_C
{
public:
	uint8                                         Pad_7D[0x3];                                       // 0x007D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_BtlUnitAI_20004EvtSuika_C;       // 0x0080(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	int32                                         ターン毎;                                          // 0x0088(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         行動数;                                            // 0x008C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         溜め毎;                                            // 0x0090(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	int32 ExecuteInner();
	void ExecuteUbergraph_BP_BtlUnitAI_20004EvtSuika(int32 EntryPoint);
	void Initialize();
	void イベント(bool* NewParam);
	void 最後のイベント();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_BtlUnitAI_20004EvtSuika_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_BtlUnitAI_20004EvtSuika_C")
	}
	static class UBP_BtlUnitAI_20004EvtSuika_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_BtlUnitAI_20004EvtSuika_C>();
	}
};
DUMPER7_ASSERTS_UBP_BtlUnitAI_20004EvtSuika_C;

SDK_NAMESPACE_END
