#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BtlUnitAI_672Nunki1B

#include "Basic.hpp"

#include "BP_BtlUnitAI_classes.hpp"
#include "mucha_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_BtlUnitAI_672Nunki1B.BP_BtlUnitAI_672Nunki1B_C
// 0x0028 (0x00A8 - 0x0080)
class UBP_BtlUnitAI_672Nunki1B_C final : public UBP_BtlUnitAI_C
{
public:
	uint8                                         Pad_7D[0x3];                                       // 0x007D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         ターン毎;                                          // 0x0080(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          始めてHP50_以下になった;                           // 0x0084(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_85[0x3];                                       // 0x0085(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         行動数;                                            // 0x0088(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_8C[0x4];                                       // 0x008C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        HP割合;                                            // 0x0090(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        形態変化HP割合;                                    // 0x0098(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         形態変化;                                          // 0x00A0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          食いしばりダメージ補正;                            // 0x00A4(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          形態変化予約;                                      // 0x00A5(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          形態変化済み;                                      // 0x00A6(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	int32 ExecuteBreakRecoveryInner();
	int32 ExecuteInner();
	int32 ExecuteRecieveDamageInner(class ACPP_BtlUnit* pAttacker, const int32 SkillId, const EeResistance resistance, const EeSkillDamageType DamageType);
	int32 ExecuteSkillActionEndInner();
	int32 ThinkInner();
	void その他属性();
	void バフデバフ();
	void 土パターン();
	void 形態変化HP判定(bool* NewParam);
	void 形態変化フロー();
	void 風パターン();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_BtlUnitAI_672Nunki1B_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_BtlUnitAI_672Nunki1B_C")
	}
	static class UBP_BtlUnitAI_672Nunki1B_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_BtlUnitAI_672Nunki1B_C>();
	}
};
DUMPER7_ASSERTS_UBP_BtlUnitAI_672Nunki1B_C;

SDK_NAMESPACE_END
