#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BtlUnitAI_030ReceivePhysics

#include "Basic.hpp"

#include "BP_BtlUnitAI_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_BtlUnitAI_030ReceivePhysics.BP_BtlUnitAI_030ReceivePhysics_C
// 0x0000 (0x0080 - 0x0080)
class UBP_BtlUnitAI_030ReceivePhysics_C final : public UBP_BtlUnitAI_C
{
public:
	int32 ExecuteInner();
	int32 ThinkInner();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_BtlUnitAI_030ReceivePhysics_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_BtlUnitAI_030ReceivePhysics_C")
	}
	static class UBP_BtlUnitAI_030ReceivePhysics_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_BtlUnitAI_030ReceivePhysics_C>();
	}
};
DUMPER7_ASSERTS_UBP_BtlUnitAI_030ReceivePhysics_C;

SDK_NAMESPACE_END
