#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BtlUnitAI_4014Col_ZoneEater

#include "Basic.hpp"

#include "BP_BtlUnitAI_4014Col_ZoneEater_classes.hpp"
#include "BP_BtlUnitAI_4014Col_ZoneEater_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_BtlUnitAI_4014Col_ZoneEater.BP_BtlUnitAI_4014Col_ZoneEater_C.ExecuteBreakRecoveryInner
// (Event, Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

int32 UBP_BtlUnitAI_4014Col_ZoneEater_C::ExecuteBreakRecoveryInner()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlUnitAI_4014Col_ZoneEater_C", "ExecuteBreakRecoveryInner");

	Params::BP_BtlUnitAI_4014Col_ZoneEater_C_ExecuteBreakRecoveryInner Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_BtlUnitAI_4014Col_ZoneEater.BP_BtlUnitAI_4014Col_ZoneEater_C.ExecuteInner
// (Event, Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

int32 UBP_BtlUnitAI_4014Col_ZoneEater_C::ExecuteInner()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlUnitAI_4014Col_ZoneEater_C", "ExecuteInner");

	Params::BP_BtlUnitAI_4014Col_ZoneEater_C_ExecuteInner Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_BtlUnitAI_4014Col_ZoneEater.BP_BtlUnitAI_4014Col_ZoneEater_C.ExecuteRecieveDamageInner
// (Event, Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ACPP_BtlUnit*                     pAttacker                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const int32                             SkillId                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const EeResistance                      resistance                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const EeSkillDamageType                 DamageType                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

int32 UBP_BtlUnitAI_4014Col_ZoneEater_C::ExecuteRecieveDamageInner(class ACPP_BtlUnit* pAttacker, const int32 SkillId, const EeResistance resistance, const EeSkillDamageType DamageType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlUnitAI_4014Col_ZoneEater_C", "ExecuteRecieveDamageInner");

	Params::BP_BtlUnitAI_4014Col_ZoneEater_C_ExecuteRecieveDamageInner Parms{};

	Parms.pAttacker = pAttacker;
	Parms.SkillId = SkillId;
	Parms.resistance = resistance;
	Parms.DamageType = DamageType;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_BtlUnitAI_4014Col_ZoneEater.BP_BtlUnitAI_4014Col_ZoneEater_C.ExecuteSkillActionEndInner
// (Event, Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

int32 UBP_BtlUnitAI_4014Col_ZoneEater_C::ExecuteSkillActionEndInner()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlUnitAI_4014Col_ZoneEater_C", "ExecuteSkillActionEndInner");

	Params::BP_BtlUnitAI_4014Col_ZoneEater_C_ExecuteSkillActionEndInner Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_BtlUnitAI_4014Col_ZoneEater.BP_BtlUnitAI_4014Col_ZoneEater_C.ThinkInner
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

int32 UBP_BtlUnitAI_4014Col_ZoneEater_C::ThinkInner()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlUnitAI_4014Col_ZoneEater_C", "ThinkInner");

	Params::BP_BtlUnitAI_4014Col_ZoneEater_C_ThinkInner Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_BtlUnitAI_4014Col_ZoneEater.BP_BtlUnitAI_4014Col_ZoneEater_C.カウンタリセット
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_BtlUnitAI_4014Col_ZoneEater_C::カウンタリセット()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlUnitAI_4014Col_ZoneEater_C", "カウンタリセット");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BtlUnitAI_4014Col_ZoneEater.BP_BtlUnitAI_4014Col_ZoneEater_C.対象判定
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   IsEmpty                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_BtlUnitAI_4014Col_ZoneEater_C::対象判定(bool* IsEmpty)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlUnitAI_4014Col_ZoneEater_C", "対象判定");

	Params::BP_BtlUnitAI_4014Col_ZoneEater_C_対象判定 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (IsEmpty != nullptr)
		*IsEmpty = Parms.IsEmpty;
}


// Function BP_BtlUnitAI_4014Col_ZoneEater.BP_BtlUnitAI_4014Col_ZoneEater_C.攻撃パターン3
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_BtlUnitAI_4014Col_ZoneEater_C::攻撃パターン3()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlUnitAI_4014Col_ZoneEater_C", "攻撃パターン3");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BtlUnitAI_4014Col_ZoneEater.BP_BtlUnitAI_4014Col_ZoneEater_C.攻撃パターン4
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_BtlUnitAI_4014Col_ZoneEater_C::攻撃パターン4()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlUnitAI_4014Col_ZoneEater_C", "攻撃パターン4");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BtlUnitAI_4014Col_ZoneEater.BP_BtlUnitAI_4014Col_ZoneEater_C.攻撃パターン5
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_BtlUnitAI_4014Col_ZoneEater_C::攻撃パターン5()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlUnitAI_4014Col_ZoneEater_C", "攻撃パターン5");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
