#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BtlUnitAI_2069_Evt_LassWell

#include "Basic.hpp"

#include "mucha_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BP_BtlUnitAI_2069_Evt_LassWell.BP_BtlUnitAI_2069_Evt_LassWell_C.ExecuteInner
// 0x0004 (0x0004 - 0x0000)
struct BP_BtlUnitAI_2069_Evt_LassWell_C_ExecuteInner final
{
public:
	int32                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_BtlUnitAI_2069_Evt_LassWell_C_ExecuteInner;

// Function BP_BtlUnitAI_2069_Evt_LassWell.BP_BtlUnitAI_2069_Evt_LassWell_C.ExecuteRecieveDamageInner
// 0x0020 (0x0020 - 0x0000)
struct BP_BtlUnitAI_2069_Evt_LassWell_C_ExecuteRecieveDamageInner final
{
public:
	class ACPP_BtlUnit*                           pAttacker;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         SkillId;                                           // 0x0008(0x0004)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EeResistance                                  resistance;                                        // 0x000C(0x0001)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EeSkillDamageType                             DamageType;                                        // 0x000D(0x0001)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_E[0x2];                                        // 0x000E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         ReturnValue;                                       // 0x0010(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_MakeLiteralName_ReturnValue;              // 0x0014(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HP___ReturnValue;                         // 0x001C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_BtlUnitAI_2069_Evt_LassWell_C_ExecuteRecieveDamageInner;

// Function BP_BtlUnitAI_2069_Evt_LassWell.BP_BtlUnitAI_2069_Evt_LassWell_C.ExecuteUbergraph_BP_BtlUnitAI_2069_Evt_LassWell
// 0x0004 (0x0004 - 0x0000)
struct BP_BtlUnitAI_2069_Evt_LassWell_C_ExecuteUbergraph_BP_BtlUnitAI_2069_Evt_LassWell final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_BtlUnitAI_2069_Evt_LassWell_C_ExecuteUbergraph_BP_BtlUnitAI_2069_Evt_LassWell;

// Function BP_BtlUnitAI_2069_Evt_LassWell.BP_BtlUnitAI_2069_Evt_LassWell_C.ThinkInner
// 0x0014 (0x0014 - 0x0000)
struct BP_BtlUnitAI_2069_Evt_LassWell_C_ThinkInner final
{
public:
	int32                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GreaterEqual_IntInt_ReturnValue;          // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable;                                 // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetSkillIdInSkillList_ReturnValue;        // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_BtlUnitAI_2069_Evt_LassWell_C_ThinkInner;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
