#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BtlUnitAI_2046Morbol

#include "Basic.hpp"

#include "BP_BtlUnitAI_2046Morbol_classes.hpp"
#include "BP_BtlUnitAI_2046Morbol_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_BtlUnitAI_2046Morbol.BP_BtlUnitAI_2046Morbol_C.1ターン目
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_BtlUnitAI_2046Morbol_C::Oneターン目()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlUnitAI_2046Morbol_C", "1ターン目");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BtlUnitAI_2046Morbol.BP_BtlUnitAI_2046Morbol_C.2ターン目
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_BtlUnitAI_2046Morbol_C::Twoターン目()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlUnitAI_2046Morbol_C", "2ターン目");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BtlUnitAI_2046Morbol.BP_BtlUnitAI_2046Morbol_C.3ターン目
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_BtlUnitAI_2046Morbol_C::Threeターン目()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlUnitAI_2046Morbol_C", "3ターン目");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BtlUnitAI_2046Morbol.BP_BtlUnitAI_2046Morbol_C.ExecuteInner
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

int32 UBP_BtlUnitAI_2046Morbol_C::ExecuteInner()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlUnitAI_2046Morbol_C", "ExecuteInner");

	Params::BP_BtlUnitAI_2046Morbol_C_ExecuteInner Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_BtlUnitAI_2046Morbol.BP_BtlUnitAI_2046Morbol_C.ExecuteRecieveDamageInner
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ACPP_BtlUnit*                     pAttacker                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const int32                             SkillId                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const EeResistance                      resistance                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const EeSkillDamageType                 DamageType                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

int32 UBP_BtlUnitAI_2046Morbol_C::ExecuteRecieveDamageInner(class ACPP_BtlUnit* pAttacker, const int32 SkillId, const EeResistance resistance, const EeSkillDamageType DamageType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlUnitAI_2046Morbol_C", "ExecuteRecieveDamageInner");

	Params::BP_BtlUnitAI_2046Morbol_C_ExecuteRecieveDamageInner Parms{};

	Parms.pAttacker = pAttacker;
	Parms.SkillId = SkillId;
	Parms.resistance = resistance;
	Parms.DamageType = DamageType;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_BtlUnitAI_2046Morbol.BP_BtlUnitAI_2046Morbol_C.ThinkInner
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

int32 UBP_BtlUnitAI_2046Morbol_C::ThinkInner()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlUnitAI_2046Morbol_C", "ThinkInner");

	Params::BP_BtlUnitAI_2046Morbol_C_ThinkInner Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_BtlUnitAI_2046Morbol.BP_BtlUnitAI_2046Morbol_C.パターン変化後
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_BtlUnitAI_2046Morbol_C::パターン変化後()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlUnitAI_2046Morbol_C", "パターン変化後");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
