#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BtlUnitAI_440Liquid_Thunder

#include "Basic.hpp"

#include "BP_BtlUnitAI_440Liquid_Thunder_classes.hpp"
#include "BP_BtlUnitAI_440Liquid_Thunder_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_BtlUnitAI_440Liquid_Thunder.BP_BtlUnitAI_440Liquid_Thunder_C.ExecuteInner
// (Event, Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

int32 UBP_BtlUnitAI_440Liquid_Thunder_C::ExecuteInner()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlUnitAI_440Liquid_Thunder_C", "ExecuteInner");

	Params::BP_BtlUnitAI_440Liquid_Thunder_C_ExecuteInner Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_BtlUnitAI_440Liquid_Thunder.BP_BtlUnitAI_440Liquid_Thunder_C.ExexuteActionResetInner
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

int32 UBP_BtlUnitAI_440Liquid_Thunder_C::ExexuteActionResetInner()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlUnitAI_440Liquid_Thunder_C", "ExexuteActionResetInner");

	Params::BP_BtlUnitAI_440Liquid_Thunder_C_ExexuteActionResetInner Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_BtlUnitAI_440Liquid_Thunder.BP_BtlUnitAI_440Liquid_Thunder_C.ThinkInner
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

int32 UBP_BtlUnitAI_440Liquid_Thunder_C::ThinkInner()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlUnitAI_440Liquid_Thunder_C", "ThinkInner");

	Params::BP_BtlUnitAI_440Liquid_Thunder_C_ThinkInner Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_BtlUnitAI_440Liquid_Thunder.BP_BtlUnitAI_440Liquid_Thunder_C.攻撃パターン3
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_BtlUnitAI_440Liquid_Thunder_C::攻撃パターン3()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlUnitAI_440Liquid_Thunder_C", "攻撃パターン3");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BtlUnitAI_440Liquid_Thunder.BP_BtlUnitAI_440Liquid_Thunder_C.攻撃パターン4
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_BtlUnitAI_440Liquid_Thunder_C::攻撃パターン4()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BtlUnitAI_440Liquid_Thunder_C", "攻撃パターン4");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
