#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_EventShake_Common_HandShake_Loop

#include "Basic.hpp"

#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_EventShake_Common_HandShake_Loop.BP_EventShake_Common_HandShake_Loop_C
// 0x0000 (0x00E0 - 0x00E0)
class UBP_EventShake_Common_HandShake_Loop_C final : public UCameraShakeBase
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_EventShake_Common_HandShake_Loop_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_EventShake_Common_HandShake_Loop_C")
	}
	static class UBP_EventShake_Common_HandShake_Loop_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_EventShake_Common_HandShake_Loop_C>();
	}
};
DUMPER7_ASSERTS_UBP_EventShake_Common_HandShake_Loop_C;

SDK_NAMESPACE_END
