#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_EncountPrimitive

#include "Basic.hpp"

#include "BP_EncountPrimitive_classes.hpp"
#include "BP_EncountPrimitive_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_EncountPrimitive.BP_EncountPrimitive_C.ExecuteUbergraph_BP_EncountPrimitive
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EncountPrimitive_C::ExecuteUbergraph_BP_EncountPrimitive(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EncountPrimitive_C", "ExecuteUbergraph_BP_EncountPrimitive");

	Params::BP_EncountPrimitive_C_ExecuteUbergraph_BP_EncountPrimitive Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EncountPrimitive.BP_EncountPrimitive_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_EncountPrimitive_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EncountPrimitive_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
