#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FinishCmdEffect

#include "Basic.hpp"

#include "mucha_structs.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BP_FinishCmdEffect.BP_FinishCmdEffect_C.ExecuteUbergraph_BP_FinishCmdEffect
// 0x0004 (0x0004 - 0x0000)
struct BP_FinishCmdEffect_C_ExecuteUbergraph_BP_FinishCmdEffect final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_FinishCmdEffect_C_ExecuteUbergraph_BP_FinishCmdEffect;

// Function BP_FinishCmdEffect.BP_FinishCmdEffect_C.ReflectNiagaraSystem
// 0x0148 (0x0148 - 0x0000)
struct BP_FinishCmdEffect_C_ReflectNiagaraSystem final
{
public:
	struct FFinishCmdEffectProperty               CallFunc_Map_Find_Value;                           // 0x0000(0x0040)(NoDestructor)
	bool                                          CallFunc_Map_Find_ReturnValue;                     // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_41[0x7];                                       // 0x0041(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             CallFunc_K2_SetRelativeLocation_SweepHitResult;    // 0x0048(0x0100)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
};
DUMPER7_ASSERTS_BP_FinishCmdEffect_C_ReflectNiagaraSystem;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
