#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_OP_EntryItem

#include "Basic.hpp"

#include "mucha_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_OP_EntryItem.BP_OP_EntryItem_C
// 0x0000 (0x0458 - 0x0458)
class UBP_OP_EntryItem_C final : public UCPP_CommonMenu_EntryItem
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_OP_EntryItem_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_OP_EntryItem_C")
	}
	static class UBP_OP_EntryItem_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_OP_EntryItem_C>();
	}
};
DUMPER7_ASSERTS_UBP_OP_EntryItem_C;

SDK_NAMESPACE_END
