#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_VisionUpgradeListItem

#include "Basic.hpp"

#include "GameplayTags_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BP_VisionUpgradeListItem.BP_VisionUpgradeListItem_C.SetEntryIndex
// 0x0004 (0x0004 - 0x0000)
struct BP_VisionUpgradeListItem_C_SetEntryIndex final
{
public:
	int32                                         InIndex;                                           // 0x0000(0x0004)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_VisionUpgradeListItem_C_SetEntryIndex;

// Function BP_VisionUpgradeListItem.BP_VisionUpgradeListItem_C.SetEntryTag
// 0x0008 (0x0008 - 0x0000)
struct BP_VisionUpgradeListItem_C_SetEntryTag final
{
public:
	struct FGameplayTag                           InTag;                                             // 0x0000(0x0008)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_VisionUpgradeListItem_C_SetEntryTag;

// Function BP_VisionUpgradeListItem.BP_VisionUpgradeListItem_C.SetIsInvalid
// 0x0001 (0x0001 - 0x0000)
struct BP_VisionUpgradeListItem_C_SetIsInvalid final
{
public:
	bool                                          InIsValid;                                         // 0x0000(0x0001)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_VisionUpgradeListItem_C_SetIsInvalid;

// Function BP_VisionUpgradeListItem.BP_VisionUpgradeListItem_C.SetUnitId
// 0x0004 (0x0004 - 0x0000)
struct BP_VisionUpgradeListItem_C_SetUnitId final
{
public:
	int32                                         InId;                                              // 0x0000(0x0004)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_VisionUpgradeListItem_C_SetUnitId;

// Function BP_VisionUpgradeListItem.BP_VisionUpgradeListItem_C.SetVisionId
// 0x0004 (0x0004 - 0x0000)
struct BP_VisionUpgradeListItem_C_SetVisionId final
{
public:
	int32                                         InId;                                              // 0x0000(0x0004)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_VisionUpgradeListItem_C_SetVisionId;

// Function BP_VisionUpgradeListItem.BP_VisionUpgradeListItem_C.GetEntryIndex
// 0x0004 (0x0004 - 0x0000)
struct BP_VisionUpgradeListItem_C_GetEntryIndex final
{
public:
	int32                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_VisionUpgradeListItem_C_GetEntryIndex;

// Function BP_VisionUpgradeListItem.BP_VisionUpgradeListItem_C.GetEntryTag
// 0x0008 (0x0008 - 0x0000)
struct BP_VisionUpgradeListItem_C_GetEntryTag final
{
public:
	struct FGameplayTag                           OutTag;                                            // 0x0000(0x0008)(Parm, OutParm, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_VisionUpgradeListItem_C_GetEntryTag;

// Function BP_VisionUpgradeListItem.BP_VisionUpgradeListItem_C.GetIsInvalid
// 0x0001 (0x0001 - 0x0000)
struct BP_VisionUpgradeListItem_C_GetIsInvalid final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_VisionUpgradeListItem_C_GetIsInvalid;

// Function BP_VisionUpgradeListItem.BP_VisionUpgradeListItem_C.GetUnitId
// 0x0004 (0x0004 - 0x0000)
struct BP_VisionUpgradeListItem_C_GetUnitId final
{
public:
	int32                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_VisionUpgradeListItem_C_GetUnitId;

// Function BP_VisionUpgradeListItem.BP_VisionUpgradeListItem_C.GetVisionId
// 0x0004 (0x0004 - 0x0000)
struct BP_VisionUpgradeListItem_C_GetVisionId final
{
public:
	int32                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_VisionUpgradeListItem_C_GetVisionId;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
