#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CCSS_BtlListPadding

#include "Basic.hpp"

#include "mucha_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass CCSS_BtlListPadding.CCSS_BtlListPadding_C
// 0x0000 (0x0038 - 0x0038)
class UCCSS_BtlListPadding_C final : public UCommonContentSlotStyle
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("CCSS_BtlListPadding_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CCSS_BtlListPadding_C")
	}
	static class UCCSS_BtlListPadding_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCCSS_BtlListPadding_C>();
	}
};
DUMPER7_ASSERTS_UCCSS_BtlListPadding_C;

SDK_NAMESPACE_END
