#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CSBS_Entry_M_Height

#include "Basic.hpp"

#include "mucha_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass CSBS_Entry_M_Height.CSBS_Entry_M_Height_C
// 0x0000 (0x0050 - 0x0050)
class UCSBS_Entry_M_Height_C final : public UCPP_CommonSizeBoxStyle
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("CSBS_Entry_M_Height_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CSBS_Entry_M_Height_C")
	}
	static class UCSBS_Entry_M_Height_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCSBS_Entry_M_Height_C>();
	}
};
DUMPER7_ASSERTS_UCSBS_Entry_M_Height_C;

SDK_NAMESPACE_END
