#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VM_BtlCmdUnitSelect

#include "Basic.hpp"

#include "mucha_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass VM_BtlCmdUnitSelect.VM_BtlCmdUnitSelect_C
// 0x0000 (0x02D0 - 0x02D0)
class UVM_BtlCmdUnitSelect_C final : public UCPP_VM_BtlCmdUnitSelect
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("VM_BtlCmdUnitSelect_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"VM_BtlCmdUnitSelect_C")
	}
	static class UVM_BtlCmdUnitSelect_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UVM_BtlCmdUnitSelect_C>();
	}
};
DUMPER7_ASSERTS_UVM_BtlCmdUnitSelect_C;

SDK_NAMESPACE_END
