#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VM_EncountSensor

#include "Basic.hpp"

#include "mucha_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass VM_EncountSensor.VM_EncountSensor_C
// 0x0000 (0x0078 - 0x0078)
class UVM_EncountSensor_C final : public UCPP_VM_EncountSensor
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("VM_EncountSensor_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"VM_EncountSensor_C")
	}
	static class UVM_EncountSensor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UVM_EncountSensor_C>();
	}
};
DUMPER7_ASSERTS_UVM_EncountSensor_C;

SDK_NAMESPACE_END
