#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VM_MiniMap

#include "Basic.hpp"

#include "mucha_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass VM_MiniMap.VM_MiniMap_C
// 0x0000 (0x07E0 - 0x07E0)
class UVM_MiniMap_C final : public UCPP_VM_MiniMap
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("VM_MiniMap_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"VM_MiniMap_C")
	}
	static class UVM_MiniMap_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UVM_MiniMap_C>();
	}
};
DUMPER7_ASSERTS_UVM_MiniMap_C;

SDK_NAMESPACE_END
