#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VM_UnitEquippedSkillSlot

#include "Basic.hpp"

#include "mucha_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass VM_UnitEquippedSkillSlot.VM_UnitEquippedSkillSlot_C
// 0x0000 (0x00F8 - 0x00F8)
class UVM_UnitEquippedSkillSlot_C final : public UCPP_VM_UnitEquippedSkillSlot
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("VM_UnitEquippedSkillSlot_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"VM_UnitEquippedSkillSlot_C")
	}
	static class UVM_UnitEquippedSkillSlot_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UVM_UnitEquippedSkillSlot_C>();
	}
};
DUMPER7_ASSERTS_UVM_UnitEquippedSkillSlot_C;

SDK_NAMESPACE_END
