#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_OP_RadioButton

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "mucha_structs.hpp"
#include "mucha_classes.hpp"
#include "EnhancedUI_structs.hpp"
#include "SlateCore_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_OP_RadioButton.WBP_OP_RadioButton_C
// 0x0438 (0x0D08 - 0x08D0)
class UWBP_OP_RadioButton_C final : public UCPP_OP_RadioButton
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x08D0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWBP_OP_RaduiButtonList_C*              WBP_OP_RaduiButtonList;                            // 0x08D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	int32                                         m_SelectIndex;                                     // 0x08E0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_8E4[0x4];                                      // 0x08E4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FOP_BaseMenu_EntryInfo                 In_Info;                                           // 0x08E8(0x0410)(Edit, BlueprintVisible, DisableEditOnInstance)
	int32                                         m_ItemIndex;                                       // 0x0CF8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_CFC[0x4];                                      // 0x0CFC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UCPP_VM_Option*                         m_VM_Option;                                       // 0x0D00(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void Chage_Resolution(class UCPP_MuchaDelegateValue* pValue);
	void Construct();
	void ExecuteUbergraph_WBP_OP_RadioButton(int32 EntryPoint);
	int32 GetValue();
	void InputNavigation(const EUINavigation InNavigation, const EWidgetInputEventType InEventType);
	void PreConstruct(bool IsDesignTime);
	void SelectItem(int32 InIndex);
	void SetOptionMenuEntryInfo(const struct FOP_BaseMenu_EntryInfo& InInfo);
	void SetValue(int32 InIndex);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_OP_RadioButton_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_OP_RadioButton_C")
	}
	static class UWBP_OP_RadioButton_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_OP_RadioButton_C>();
	}
};
DUMPER7_ASSERTS_UWBP_OP_RadioButton_C;

SDK_NAMESPACE_END
