#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UnitIcon

#include "Basic.hpp"

#include "WBP_UnitIcon_classes.hpp"
#include "WBP_UnitIcon_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_UnitIcon.WBP_UnitIcon_C.ExecuteUbergraph_WBP_UnitIcon
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UnitIcon_C::ExecuteUbergraph_WBP_UnitIcon(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitIcon_C", "ExecuteUbergraph_WBP_UnitIcon");

	Params::WBP_UnitIcon_C_ExecuteUbergraph_WBP_UnitIcon Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UnitIcon.WBP_UnitIcon_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UnitIcon_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitIcon_C", "PreConstruct");

	Params::WBP_UnitIcon_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UnitIcon.WBP_UnitIcon_C.SetIsWidgetEnabled
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const bool                              InIsEnabled                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UnitIcon_C::SetIsWidgetEnabled(const bool InIsEnabled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitIcon_C", "SetIsWidgetEnabled");

	Params::WBP_UnitIcon_C_SetIsWidgetEnabled Parms{};

	Parms.InIsEnabled = InIsEnabled;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UnitIcon.WBP_UnitIcon_C.SetUnitId
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const int32                             InId                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UnitIcon_C::SetUnitId(const int32 InId)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitIcon_C", "SetUnitId");

	Params::WBP_UnitIcon_C_SetUnitId Parms{};

	Parms.InId = InId;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UnitIcon.WBP_UnitIcon_C.SetUnitId_View
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   InId                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UnitIcon_C::SetUnitId_View(int32 InId)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitIcon_C", "SetUnitId_View");

	Params::WBP_UnitIcon_C_SetUnitId_View Parms{};

	Parms.InId = InId;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UnitIcon.WBP_UnitIcon_C.GetIsWidgetEnabled
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool UWBP_UnitIcon_C::GetIsWidgetEnabled() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitIcon_C", "GetIsWidgetEnabled");

	Params::WBP_UnitIcon_C_GetIsWidgetEnabled Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_UnitIcon.WBP_UnitIcon_C.GetUnitId
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

int32 UWBP_UnitIcon_C::GetUnitId() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitIcon_C", "GetUnitId");

	Params::WBP_UnitIcon_C_GetUnitId Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


SDK_NAMESPACE_END
