#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_IconTextLayout

#include "Basic.hpp"

#include "UMG_structs.hpp"
#include "GameplayTags_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function WBP_IconTextLayout.WBP_IconTextLayout_C.SetData
// 0x0030 (0x0030 - 0x0000)
struct WBP_IconTextLayout_C_SetData final
{
public:
	struct FGameplayTag                           InIconTag;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
	class FText                                   InText;                                            // 0x0008(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm)
	TScriptInterface<class ICPP_BI_GameplayTagBrush> CallFunc_SetBrushTag_self_CastInput;            // 0x0018(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_GameplayTag_ReturnValue;       // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              CallFunc_Cast_SlateVisibility_From_Bool_ReturnValue; // 0x0029(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_IconTextLayout_C_SetData;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
