#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_SkillCost_Limit

#include "Basic.hpp"

#include "WBP_SkillCost_Limit_classes.hpp"
#include "WBP_SkillCost_Limit_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_SkillCost_Limit.WBP_SkillCost_Limit_C.SetCostValue
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   InValue                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_SkillCost_Limit_C::SetCostValue(int32 InValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SkillCost_Limit_C", "SetCostValue");

	Params::WBP_SkillCost_Limit_C_SetCostValue Parms{};

	Parms.InValue = InValue;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
