#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ListEntryButtonBase

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "EnhancedUI_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function WBP_ListEntryButtonBase.WBP_ListEntryButtonBase_C.BP_OnIsFocused
// 0x0020 (0x0020 - 0x0000)
struct WBP_ListEntryButtonBase_C_BP_OnIsFocused final
{
public:
	bool                                          IsFocused;                                         // 0x0000(0x0001)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FButtonEventTriggeredData              InTriggeredData;                                   // 0x0008(0x0018)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, ContainsInstancedReference)
};
DUMPER7_ASSERTS_WBP_ListEntryButtonBase_C_BP_OnIsFocused;

// Function WBP_ListEntryButtonBase.WBP_ListEntryButtonBase_C.CreateCursor
// 0x0038 (0x0038 - 0x0000)
struct WBP_ListEntryButtonBase_C_CreateCursor final
{
public:
	class UOverlaySlot*                           L_Slot;                                            // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValidClass_ReturnValue;                 // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UOverlaySlot*                           CallFunc_AddChildToOverlay_ReturnValue;            // 0x0010(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FMargin                                K2Node_MakeStruct_Margin;                          // 0x0018(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0029(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2A[0x6];                                       // 0x002A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                CallFunc_SpawnObject_ReturnValue;                  // 0x0030(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_ListEntryButtonBase_C_CreateCursor;

// Function WBP_ListEntryButtonBase.WBP_ListEntryButtonBase_C.ExecuteUbergraph_WBP_ListEntryButtonBase
// 0x0004 (0x0004 - 0x0000)
struct WBP_ListEntryButtonBase_C_ExecuteUbergraph_WBP_ListEntryButtonBase final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_ListEntryButtonBase_C_ExecuteUbergraph_WBP_ListEntryButtonBase;

// Function WBP_ListEntryButtonBase.WBP_ListEntryButtonBase_C.SetForceVisibleCursor
// 0x0001 (0x0001 - 0x0000)
struct WBP_ListEntryButtonBase_C_SetForceVisibleCursor final
{
public:
	bool                                          IsForce;                                           // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_ListEntryButtonBase_C_SetForceVisibleCursor;

// Function WBP_ListEntryButtonBase.WBP_ListEntryButtonBase_C.SyncFocusAppearance
// 0x0030 (0x0030 - 0x0000)
struct WBP_ListEntryButtonBase_C_SyncFocusAppearance final
{
public:
	bool                                          L_IsDisplay;                                       // 0x0000(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class ICPP_EU_BI_OpenClose>  CallFunc_CloseWidget_self_CastInput;               // 0x0008(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class ICPP_EU_BI_OpenClose>  CallFunc_OpenWidget_self_CastInput;                // 0x0018(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetIsFocused_ReturnValue;                 // 0x0029(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x002A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_ListEntryButtonBase_C_SyncFocusAppearance;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
