#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CircleGauge

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function WBP_CircleGauge.WBP_CircleGauge_C.ExecuteUbergraph_WBP_CircleGauge
// 0x0008 (0x0008 - 0x0000)
struct WBP_CircleGauge_C_ExecuteUbergraph_WBP_CircleGauge final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_CircleGauge_C_ExecuteUbergraph_WBP_CircleGauge;

// Function WBP_CircleGauge.WBP_CircleGauge_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct WBP_CircleGauge_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_CircleGauge_C_PreConstruct;

// Function WBP_CircleGauge.WBP_CircleGauge_C.SetBrush
// 0x0010 (0x0010 - 0x0000)
struct WBP_CircleGauge_C_SetBrush final
{
public:
	class UMaterialInstanceDynamic*               CallFunc_CreateDynamicMaterialInstance_ReturnValue; // 0x0000(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_CircleGauge_C_SetBrush;

// Function WBP_CircleGauge.WBP_CircleGauge_C.SetColor
// 0x0010 (0x0010 - 0x0000)
struct WBP_CircleGauge_C_SetColor final
{
public:
	struct FLinearColor                           InColor;                                           // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_CircleGauge_C_SetColor;

// Function WBP_CircleGauge.WBP_CircleGauge_C.SetGradationColor
// 0x0020 (0x0020 - 0x0000)
struct WBP_CircleGauge_C_SetGradationColor final
{
public:
	struct FLinearColor                           InBaseColor;                                       // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           InToColor;                                         // 0x0010(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_CircleGauge_C_SetGradationColor;

// Function WBP_CircleGauge.WBP_CircleGauge_C.SetHoleWidth
// 0x0010 (0x0010 - 0x0000)
struct WBP_CircleGauge_C_SetHoleWidth final
{
public:
	double                                        InHoleWidth;                                       // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetScalarParameterValue_Value_ImplicitCast; // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_CircleGauge_C_SetHoleWidth;

// Function WBP_CircleGauge.WBP_CircleGauge_C.SetPercent
// 0x0018 (0x0018 - 0x0000)
struct WBP_CircleGauge_C_SetPercent final
{
public:
	double                                        InPercent;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Clamp_Float_0_1_ReturnValue;              // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x000C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D[0x3];                                        // 0x000D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Clamp_Float_0_1_x_ImplicitCast;           // 0x0010(0x0004)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_CircleGauge_C_SetPercent;

// Function WBP_CircleGauge.WBP_CircleGauge_C.SetSectionNum
// 0x0018 (0x0018 - 0x0000)
struct WBP_CircleGauge_C_SetSectionNum final
{
public:
	int32                                         InSectionNum;                                      // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Conv_IntToDouble_ReturnValue;             // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetScalarParameterValue_Value_ImplicitCast; // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_CircleGauge_C_SetSectionNum;

// Function WBP_CircleGauge.WBP_CircleGauge_C.SetThickness
// 0x0010 (0x0010 - 0x0000)
struct WBP_CircleGauge_C_SetThickness final
{
public:
	double                                        InThickness;                                       // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetScalarParameterValue_Value_ImplicitCast; // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_CircleGauge_C_SetThickness;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
