#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_OP_ResetButton

#include "Basic.hpp"

#include "EnhancedUI_structs.hpp"
#include "mucha_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function WBP_OP_ResetButton.WBP_OP_ResetButton_C.BP_OnClicked
// 0x0028 (0x0028 - 0x0000)
struct WBP_OP_ResetButton_C_BP_OnClicked final
{
public:
	struct FButtonEventTriggeredData              InTriggeredData;                                   // 0x0000(0x0018)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, ContainsInstancedReference)
	class UCPP_MuchaEventDispatcher*              CallFunc_GetGameInstanceSubsystem_ReturnValue;     // 0x0018(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UCPP_MuchaDelegateValue*                CallFunc_SpawnObject_ReturnValue;                  // 0x0020(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_OP_ResetButton_C_BP_OnClicked;

// Function WBP_OP_ResetButton.WBP_OP_ResetButton_C.BP_OnFocused
// 0x0018 (0x0018 - 0x0000)
struct WBP_OP_ResetButton_C_BP_OnFocused final
{
public:
	struct FButtonEventTriggeredData              InTriggeredData;                                   // 0x0000(0x0018)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, ContainsInstancedReference)
};
DUMPER7_ASSERTS_WBP_OP_ResetButton_C_BP_OnFocused;

// Function WBP_OP_ResetButton.WBP_OP_ResetButton_C.BP_OnUnfocused
// 0x0018 (0x0018 - 0x0000)
struct WBP_OP_ResetButton_C_BP_OnUnfocused final
{
public:
	struct FButtonEventTriggeredData              InTriggeredData;                                   // 0x0000(0x0018)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, ContainsInstancedReference)
};
DUMPER7_ASSERTS_WBP_OP_ResetButton_C_BP_OnUnfocused;

// Function WBP_OP_ResetButton.WBP_OP_ResetButton_C.SetOptionMenuEntryInfo
// 0x0410 (0x0410 - 0x0000)
struct WBP_OP_ResetButton_C_SetOptionMenuEntryInfo final
{
public:
	struct FOP_BaseMenu_EntryInfo                 InInfo;                                            // 0x0000(0x0410)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm)
};
DUMPER7_ASSERTS_WBP_OP_ResetButton_C_SetOptionMenuEntryInfo;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
