#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_BtlCmd_ItemEntry

#include "Basic.hpp"

#include "WBP_BtlCmdEntryBase_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_BtlCmd_ItemEntry.WBP_BtlCmd_ItemEntry_C
// 0x0000 (0x04C0 - 0x04C0)
class UWBP_BtlCmd_ItemEntry_C final : public UWBP_BtlCmdEntryBase_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_BtlCmd_ItemEntry_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_BtlCmd_ItemEntry_C")
	}
	static class UWBP_BtlCmd_ItemEntry_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_BtlCmd_ItemEntry_C>();
	}
};
DUMPER7_ASSERTS_UWBP_BtlCmd_ItemEntry_C;

SDK_NAMESPACE_END
