#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_BtlTimeLine_RiskIcon

#include "Basic.hpp"

#include "UMG_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function WBP_BtlTimeLine_RiskIcon.WBP_BtlTimeLine_RiskIcon_C.ExecuteUbergraph_WBP_BtlTimeLine_RiskIcon
// 0x0014 (0x0014 - 0x0000)
struct WBP_BtlTimeLine_RiskIcon_C_ExecuteUbergraph_WBP_BtlTimeLine_RiskIcon final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FWidgetAnimationHandle                 CallFunc_PlayAnimation_ReturnValue;                // 0x0004(0x0010)(NoDestructor, ContainsInstancedReference, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_BtlTimeLine_RiskIcon_C_ExecuteUbergraph_WBP_BtlTimeLine_RiskIcon;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
