#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_DemoScreenBase

#include "Basic.hpp"

#include "WBP_DemoScreenBase_classes.hpp"
#include "WBP_DemoScreenBase_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_DemoScreenBase.WBP_DemoScreenBase_C.WidgetAnimationEvt_A_Display_K2Node_WidgetAnimationEvent_0
// (BlueprintEvent)

void UWBP_DemoScreenBase_C::WidgetAnimationEvt_A_Display_K2Node_WidgetAnimationEvent_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DemoScreenBase_C", "WidgetAnimationEvt_A_Display_K2Node_WidgetAnimationEvent_0");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_DemoScreenBase.WBP_DemoScreenBase_C.UpdateActionGuideState
// (Event, Protected, BlueprintCallable, BlueprintEvent)

void UWBP_DemoScreenBase_C::UpdateActionGuideState()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DemoScreenBase_C", "UpdateActionGuideState");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_DemoScreenBase.WBP_DemoScreenBase_C.SetKeyGuideDisplay
// (Protected, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    InIs                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_DemoScreenBase_C::SetKeyGuideDisplay(bool InIs)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DemoScreenBase_C", "SetKeyGuideDisplay");

	Params::WBP_DemoScreenBase_C_SetKeyGuideDisplay Parms{};

	Parms.InIs = InIs;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_DemoScreenBase.WBP_DemoScreenBase_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_DemoScreenBase_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DemoScreenBase_C", "PreConstruct");

	Params::WBP_DemoScreenBase_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_DemoScreenBase.WBP_DemoScreenBase_C.OnRequestOpen
// (Event, Protected, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_DemoScreenBase_C::OnRequestOpen()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DemoScreenBase_C", "OnRequestOpen");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_DemoScreenBase.WBP_DemoScreenBase_C.OnRequestClose
// (Event, Protected, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_DemoScreenBase_C::OnRequestClose()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DemoScreenBase_C", "OnRequestClose");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_DemoScreenBase.WBP_DemoScreenBase_C.InputDecide
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const EWidgetInputEventType             InEventType                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_DemoScreenBase_C::InputDecide(const EWidgetInputEventType InEventType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DemoScreenBase_C", "InputDecide");

	Params::WBP_DemoScreenBase_C_InputDecide Parms{};

	Parms.InEventType = InEventType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_DemoScreenBase.WBP_DemoScreenBase_C.ExecuteUbergraph_WBP_DemoScreenBase
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_DemoScreenBase_C::ExecuteUbergraph_WBP_DemoScreenBase(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DemoScreenBase_C", "ExecuteUbergraph_WBP_DemoScreenBase");

	Params::WBP_DemoScreenBase_C_ExecuteUbergraph_WBP_DemoScreenBase Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_DemoScreenBase.WBP_DemoScreenBase_C.BP_OnFinishedOpen
// (Event, Protected, BlueprintCallable, BlueprintEvent)

void UWBP_DemoScreenBase_C::BP_OnFinishedOpen()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DemoScreenBase_C", "BP_OnFinishedOpen");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
