#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CmnWindowFrame

#include "Basic.hpp"

#include "mucha_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function WBP_CmnWindowFrame.WBP_CmnWindowFrame_C.BP_ReflectStyle
// 0x00E0 (0x00E0 - 0x0000)
struct WBP_CmnWindowFrame_C_BP_ReflectStyle final
{
public:
	struct FCmnWindow_FrameStyle                  CallFunc_GetFrameStyle_ReturnValue;                // 0x0000(0x00D0)()
	class UImage*                                 CallFunc_GetFrameImage_ReturnValue;                // 0x00D0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UOverlaySlot*                           CallFunc_SlotAsOverlaySlot_ReturnValue;            // 0x00D8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_CmnWindowFrame_C_BP_ReflectStyle;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
