#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MenuEntryIcon

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "GameplayTags_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function WBP_MenuEntryIcon.WBP_MenuEntryIcon_C.ExecuteUbergraph_WBP_MenuEntryIcon
// 0x0008 (0x0008 - 0x0000)
struct WBP_MenuEntryIcon_C_ExecuteUbergraph_WBP_MenuEntryIcon final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_MenuEntryIcon_C_ExecuteUbergraph_WBP_MenuEntryIcon;

// Function WBP_MenuEntryIcon.WBP_MenuEntryIcon_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct WBP_MenuEntryIcon_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_MenuEntryIcon_C_PreConstruct;

// Function WBP_MenuEntryIcon.WBP_MenuEntryIcon_C.SetBrushColor
// 0x0010 (0x0010 - 0x0000)
struct WBP_MenuEntryIcon_C_SetBrushColor final
{
public:
	struct FLinearColor                           InColor;                                           // 0x0000(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_MenuEntryIcon_C_SetBrushColor;

// Function WBP_MenuEntryIcon.WBP_MenuEntryIcon_C.SetBrushTag
// 0x0018 (0x0018 - 0x0000)
struct WBP_MenuEntryIcon_C_SetBrushTag final
{
public:
	struct FGameplayTag                           InTag;                                             // 0x0000(0x0008)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class ICPP_BI_GameplayTagBrush> CallFunc_SetBrushTag_self_CastInput;            // 0x0008(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_MenuEntryIcon_C_SetBrushTag;

// Function WBP_MenuEntryIcon.WBP_MenuEntryIcon_C.SetIconTag
// 0x0008 (0x0008 - 0x0000)
struct WBP_MenuEntryIcon_C_SetIconTag final
{
public:
	struct FGameplayTag                           InTag;                                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_MenuEntryIcon_C_SetIconTag;

// Function WBP_MenuEntryIcon.WBP_MenuEntryIcon_C.GetBrushTag
// 0x0020 (0x0020 - 0x0000)
struct WBP_MenuEntryIcon_C_GetBrushTag final
{
public:
	struct FGameplayTag                           ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ReturnParm, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class ICPP_BI_GameplayTagBrush> CallFunc_GetBrushTag_self_CastInput;            // 0x0008(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           CallFunc_GetBrushTag_ReturnValue;                  // 0x0018(0x0008)(NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_MenuEntryIcon_C_GetBrushTag;

// Function WBP_MenuEntryIcon.WBP_MenuEntryIcon_C.IsValidBrush
// 0x0001 (0x0001 - 0x0000)
struct WBP_MenuEntryIcon_C_IsValidBrush final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_MenuEntryIcon_C_IsValidBrush;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
