#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UnitEquippedSkillEntry

#include "Basic.hpp"

#include "WBP_UnitEquippedSkillEntry_classes.hpp"
#include "WBP_UnitEquippedSkillEntry_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_UnitEquippedSkillEntry.WBP_UnitEquippedSkillEntry_C.ExecuteUbergraph_WBP_UnitEquippedSkillEntry
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UnitEquippedSkillEntry_C::ExecuteUbergraph_WBP_UnitEquippedSkillEntry(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitEquippedSkillEntry_C", "ExecuteUbergraph_WBP_UnitEquippedSkillEntry");

	Params::WBP_UnitEquippedSkillEntry_C_ExecuteUbergraph_WBP_UnitEquippedSkillEntry Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UnitEquippedSkillEntry.WBP_UnitEquippedSkillEntry_C.OnInitialized
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_UnitEquippedSkillEntry_C::OnInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitEquippedSkillEntry_C", "OnInitialized");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UnitEquippedSkillEntry.WBP_UnitEquippedSkillEntry_C.SetActionKey
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FActionKey&                InKey                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)

void UWBP_UnitEquippedSkillEntry_C::SetActionKey(const struct FActionKey& InKey)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitEquippedSkillEntry_C", "SetActionKey");

	Params::WBP_UnitEquippedSkillEntry_C_SetActionKey Parms{};

	Parms.InKey = std::move(InKey);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UnitEquippedSkillEntry.WBP_UnitEquippedSkillEntry_C.SetEntryIndex
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const int32                             InIndex                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UnitEquippedSkillEntry_C::SetEntryIndex(const int32 InIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitEquippedSkillEntry_C", "SetEntryIndex");

	Params::WBP_UnitEquippedSkillEntry_C_SetEntryIndex Parms{};

	Parms.InIndex = InIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UnitEquippedSkillEntry.WBP_UnitEquippedSkillEntry_C.SetEntryTag
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayTag&              InTag                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor, HasGetValueTypeHash)

void UWBP_UnitEquippedSkillEntry_C::SetEntryTag(const struct FGameplayTag& InTag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitEquippedSkillEntry_C", "SetEntryTag");

	Params::WBP_UnitEquippedSkillEntry_C_SetEntryTag Parms{};

	Parms.InTag = std::move(InTag);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UnitEquippedSkillEntry.WBP_UnitEquippedSkillEntry_C.SetInventoryActionData
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FInventoryActionData&      InData                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void UWBP_UnitEquippedSkillEntry_C::SetInventoryActionData(const struct FInventoryActionData& InData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitEquippedSkillEntry_C", "SetInventoryActionData");

	Params::WBP_UnitEquippedSkillEntry_C_SetInventoryActionData Parms{};

	Parms.InData = std::move(InData);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UnitEquippedSkillEntry.WBP_UnitEquippedSkillEntry_C.SetIsInvalid
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const bool                              InIsValid                                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UnitEquippedSkillEntry_C::SetIsInvalid(const bool InIsValid)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitEquippedSkillEntry_C", "SetIsInvalid");

	Params::WBP_UnitEquippedSkillEntry_C_SetIsInvalid Parms{};

	Parms.InIsValid = InIsValid;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UnitEquippedSkillEntry.WBP_UnitEquippedSkillEntry_C.SetVM_UnitEquippedSkillSlot
// (Final, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UVM_UnitEquippedSkillSlot_C*      ViewModel                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_UnitEquippedSkillEntry_C::SetVM_UnitEquippedSkillSlot(class UVM_UnitEquippedSkillSlot_C* ViewModel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitEquippedSkillEntry_C", "SetVM_UnitEquippedSkillSlot");

	Params::WBP_UnitEquippedSkillEntry_C_SetVM_UnitEquippedSkillSlot Parms{};

	Parms.ViewModel = ViewModel;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UnitEquippedSkillEntry.WBP_UnitEquippedSkillEntry_C.__f06616c3-4351-d98d-7d09-e3851f66aee3_SourceToDest
// (Final, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UWBP_UnitEquippedSkillEntry_C::__f06616c3_4351_d98d_7d09_e3851f66aee3_SourceToDest() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitEquippedSkillEntry_C", "__f06616c3-4351-d98d-7d09-e3851f66aee3_SourceToDest");

	Params::WBP_UnitEquippedSkillEntry_C___f06616c3_4351_d98d_7d09_e3851f66aee3_SourceToDest Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_UnitEquippedSkillEntry.WBP_UnitEquippedSkillEntry_C.GetActionKey
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// struct FActionKey                       ReturnValue                                            (Parm, OutParm, ReturnParm, NoDestructor, HasGetValueTypeHash)

struct FActionKey UWBP_UnitEquippedSkillEntry_C::GetActionKey() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitEquippedSkillEntry_C", "GetActionKey");

	Params::WBP_UnitEquippedSkillEntry_C_GetActionKey Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_UnitEquippedSkillEntry.WBP_UnitEquippedSkillEntry_C.GetEntryIndex
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

int32 UWBP_UnitEquippedSkillEntry_C::GetEntryIndex() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitEquippedSkillEntry_C", "GetEntryIndex");

	Params::WBP_UnitEquippedSkillEntry_C_GetEntryIndex Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_UnitEquippedSkillEntry.WBP_UnitEquippedSkillEntry_C.GetEntryTag
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// struct FGameplayTag*                    OutTag                                                 (Parm, OutParm, NoDestructor, HasGetValueTypeHash)

void UWBP_UnitEquippedSkillEntry_C::GetEntryTag(struct FGameplayTag* OutTag) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitEquippedSkillEntry_C", "GetEntryTag");

	Params::WBP_UnitEquippedSkillEntry_C_GetEntryTag Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (OutTag != nullptr)
		*OutTag = std::move(Parms.OutTag);
}


// Function WBP_UnitEquippedSkillEntry.WBP_UnitEquippedSkillEntry_C.GetInventoryActionData
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// struct FInventoryActionData             ReturnValue                                            (Parm, OutParm, ReturnParm, NoDestructor)

struct FInventoryActionData UWBP_UnitEquippedSkillEntry_C::GetInventoryActionData() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitEquippedSkillEntry_C", "GetInventoryActionData");

	Params::WBP_UnitEquippedSkillEntry_C_GetInventoryActionData Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_UnitEquippedSkillEntry.WBP_UnitEquippedSkillEntry_C.GetIsInvalid
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool UWBP_UnitEquippedSkillEntry_C::GetIsInvalid() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitEquippedSkillEntry_C", "GetIsInvalid");

	Params::WBP_UnitEquippedSkillEntry_C_GetIsInvalid Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


SDK_NAMESPACE_END
