#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PrimaryButton

#include "Basic.hpp"

#include "WBP_PrimaryButton_classes.hpp"
#include "WBP_PrimaryButton_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_PrimaryButton.WBP_PrimaryButton_C.BP_OnIsFocused
// (Event, Protected, BlueprintCallable, BlueprintEvent)
// Parameters:
// const bool                              IsFocused                                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FButtonEventTriggeredData& InTriggeredData                                        (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, ContainsInstancedReference)

void UWBP_PrimaryButton_C::BP_OnIsFocused(const bool IsFocused, const struct FButtonEventTriggeredData& InTriggeredData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PrimaryButton_C", "BP_OnIsFocused");

	Params::WBP_PrimaryButton_C_BP_OnIsFocused Parms{};

	Parms.IsFocused = IsFocused;
	Parms.InTriggeredData = std::move(InTriggeredData);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PrimaryButton.WBP_PrimaryButton_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_PrimaryButton_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PrimaryButton_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_PrimaryButton.WBP_PrimaryButton_C.ExecuteUbergraph_WBP_PrimaryButton
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_PrimaryButton_C::ExecuteUbergraph_WBP_PrimaryButton(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PrimaryButton_C", "ExecuteUbergraph_WBP_PrimaryButton");

	Params::WBP_PrimaryButton_C_ExecuteUbergraph_WBP_PrimaryButton Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PrimaryButton.WBP_PrimaryButton_C.SetForceVisibleCursor
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsForce                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_PrimaryButton_C::SetForceVisibleCursor(bool IsForce)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PrimaryButton_C", "SetForceVisibleCursor");

	Params::WBP_PrimaryButton_C_SetForceVisibleCursor Parms{};

	Parms.IsForce = IsForce;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PrimaryButton.WBP_PrimaryButton_C.SetIsDisplayFrame
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    InIs                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_PrimaryButton_C::SetIsDisplayFrame(bool InIs)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PrimaryButton_C", "SetIsDisplayFrame");

	Params::WBP_PrimaryButton_C_SetIsDisplayFrame Parms{};

	Parms.InIs = InIs;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PrimaryButton.WBP_PrimaryButton_C.SetIsWidgetEnabled
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const bool                              InIsEnabled                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_PrimaryButton_C::SetIsWidgetEnabled(const bool InIsEnabled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PrimaryButton_C", "SetIsWidgetEnabled");

	Params::WBP_PrimaryButton_C_SetIsWidgetEnabled Parms{};

	Parms.InIsEnabled = InIsEnabled;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PrimaryButton.WBP_PrimaryButton_C.SyncFocusAppearance
// (Private, BlueprintCallable, BlueprintEvent)

void UWBP_PrimaryButton_C::SyncFocusAppearance()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PrimaryButton_C", "SyncFocusAppearance");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
