#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MuchaDirectionalList

#include "Basic.hpp"

#include "WBP_MuchaDirectionalList_classes.hpp"
#include "WBP_MuchaDirectionalList_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_MuchaDirectionalList.WBP_MuchaDirectionalList_C.InputDirection
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const EUINavigation                     InNavigation                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const EWidgetInputEventType             InEventType                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_MuchaDirectionalList_C::InputDirection(const EUINavigation InNavigation, const EWidgetInputEventType InEventType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MuchaDirectionalList_C", "InputDirection");

	Params::WBP_MuchaDirectionalList_C_InputDirection Parms{};

	Parms.InNavigation = InNavigation;
	Parms.InEventType = InEventType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MuchaDirectionalList.WBP_MuchaDirectionalList_C.GetListItems
// (Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// const TArray<class UObject*>            ReturnValue                                            (ConstParm, Parm, OutParm, ReturnParm)

const TArray<class UObject*> UWBP_MuchaDirectionalList_C::GetListItems() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MuchaDirectionalList_C", "GetListItems");

	Params::WBP_MuchaDirectionalList_C_GetListItems Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_MuchaDirectionalList.WBP_MuchaDirectionalList_C.GetNumColumns
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

int32 UWBP_MuchaDirectionalList_C::GetNumColumns() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MuchaDirectionalList_C", "GetNumColumns");

	Params::WBP_MuchaDirectionalList_C_GetNumColumns Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_MuchaDirectionalList.WBP_MuchaDirectionalList_C.GetSkipCount
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

int32 UWBP_MuchaDirectionalList_C::GetSkipCount() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MuchaDirectionalList_C", "GetSkipCount");

	Params::WBP_MuchaDirectionalList_C_GetSkipCount Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


SDK_NAMESPACE_END
