#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UnitSsPlayerWidget

#include "Basic.hpp"

#include "WBP_UnitSsPlayerWidget_classes.hpp"
#include "WBP_UnitSsPlayerWidget_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_UnitSsPlayerWidget.WBP_UnitSsPlayerWidget_C.AddContent
// (Private, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidget*                          InContent                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class UOverlaySlot*                     ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)

class UOverlaySlot* UWBP_UnitSsPlayerWidget_C::AddContent(class UWidget* InContent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitSsPlayerWidget_C", "AddContent");

	Params::WBP_UnitSsPlayerWidget_C_AddContent Parms{};

	Parms.InContent = InContent;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_UnitSsPlayerWidget.WBP_UnitSsPlayerWidget_C.ApplySsProject
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_UnitSsPlayerWidget_C::ApplySsProject()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitSsPlayerWidget_C", "ApplySsProject");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UnitSsPlayerWidget.WBP_UnitSsPlayerWidget_C.AsyncLoadSS
// (BlueprintCallable, BlueprintEvent)

void UWBP_UnitSsPlayerWidget_C::AsyncLoadSS()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitSsPlayerWidget_C", "AsyncLoadSS");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UnitSsPlayerWidget.WBP_UnitSsPlayerWidget_C.ConvPlayableUnitId
// (Private, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// int32                                   InId                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32*                                  Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UnitSsPlayerWidget_C::ConvPlayableUnitId(int32 InId, int32* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitSsPlayerWidget_C", "ConvPlayableUnitId");

	Params::WBP_UnitSsPlayerWidget_C_ConvPlayableUnitId Parms{};

	Parms.InId = InId;

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function WBP_UnitSsPlayerWidget.WBP_UnitSsPlayerWidget_C.CreateLoadingIcon
// (Private, BlueprintCallable, BlueprintEvent)

void UWBP_UnitSsPlayerWidget_C::CreateLoadingIcon()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitSsPlayerWidget_C", "CreateLoadingIcon");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UnitSsPlayerWidget.WBP_UnitSsPlayerWidget_C.DelayFinish
// (BlueprintCallable, BlueprintEvent)

void UWBP_UnitSsPlayerWidget_C::DelayFinish()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitSsPlayerWidget_C", "DelayFinish");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UnitSsPlayerWidget.WBP_UnitSsPlayerWidget_C.ExecuteUbergraph_WBP_UnitSsPlayerWidget
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UnitSsPlayerWidget_C::ExecuteUbergraph_WBP_UnitSsPlayerWidget(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitSsPlayerWidget_C", "ExecuteUbergraph_WBP_UnitSsPlayerWidget");

	Params::WBP_UnitSsPlayerWidget_C_ExecuteUbergraph_WBP_UnitSsPlayerWidget Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UnitSsPlayerWidget.WBP_UnitSsPlayerWidget_C.FinishInitialize
// (Private, BlueprintCallable, BlueprintEvent)

void UWBP_UnitSsPlayerWidget_C::FinishInitialize()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitSsPlayerWidget_C", "FinishInitialize");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UnitSsPlayerWidget.WBP_UnitSsPlayerWidget_C.OnInitialized
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_UnitSsPlayerWidget_C::OnInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitSsPlayerWidget_C", "OnInitialized");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UnitSsPlayerWidget.WBP_UnitSsPlayerWidget_C.OnLoaded_A1B117694A1DB3D3EA3D06B05C041197
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          Loaded                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_UnitSsPlayerWidget_C::OnLoaded_A1B117694A1DB3D3EA3D06B05C041197(class UObject* Loaded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitSsPlayerWidget_C", "OnLoaded_A1B117694A1DB3D3EA3D06B05C041197");

	Params::WBP_UnitSsPlayerWidget_C_OnLoaded_A1B117694A1DB3D3EA3D06B05C041197 Parms{};

	Parms.Loaded = Loaded;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UnitSsPlayerWidget.WBP_UnitSsPlayerWidget_C.Pause
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_UnitSsPlayerWidget_C::Pause()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitSsPlayerWidget_C", "Pause");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UnitSsPlayerWidget.WBP_UnitSsPlayerWidget_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UnitSsPlayerWidget_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitSsPlayerWidget_C", "PreConstruct");

	Params::WBP_UnitSsPlayerWidget_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UnitSsPlayerWidget.WBP_UnitSsPlayerWidget_C.RemoveLoadingIcon
// (Private, BlueprintCallable, BlueprintEvent)

void UWBP_UnitSsPlayerWidget_C::RemoveLoadingIcon()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitSsPlayerWidget_C", "RemoveLoadingIcon");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UnitSsPlayerWidget.WBP_UnitSsPlayerWidget_C.Resume
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_UnitSsPlayerWidget_C::Resume()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitSsPlayerWidget_C", "Resume");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UnitSsPlayerWidget.WBP_UnitSsPlayerWidget_C.SetIsPause
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    InIs                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UnitSsPlayerWidget_C::SetIsPause(bool InIs)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitSsPlayerWidget_C", "SetIsPause");

	Params::WBP_UnitSsPlayerWidget_C_SetIsPause Parms{};

	Parms.InIs = InIs;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UnitSsPlayerWidget.WBP_UnitSsPlayerWidget_C.SetNeutralAnimationData
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FMSP_AnimationData&        InData                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void UWBP_UnitSsPlayerWidget_C::SetNeutralAnimationData(const struct FMSP_AnimationData& InData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitSsPlayerWidget_C", "SetNeutralAnimationData");

	Params::WBP_UnitSsPlayerWidget_C_SetNeutralAnimationData Parms{};

	Parms.InData = std::move(InData);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UnitSsPlayerWidget.WBP_UnitSsPlayerWidget_C.SetOneShotAnimationData
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FMSP_AnimationData&        InData                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void UWBP_UnitSsPlayerWidget_C::SetOneShotAnimationData(const struct FMSP_AnimationData& InData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitSsPlayerWidget_C", "SetOneShotAnimationData");

	Params::WBP_UnitSsPlayerWidget_C_SetOneShotAnimationData Parms{};

	Parms.InData = std::move(InData);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UnitSsPlayerWidget.WBP_UnitSsPlayerWidget_C.SetPlannedSsProject
// (Private, BlueprintCallable, BlueprintEvent)
// Parameters:
// TSoftObjectPtr<class UObject>           InSsProject                                            (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void UWBP_UnitSsPlayerWidget_C::SetPlannedSsProject(TSoftObjectPtr<class UObject> InSsProject)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitSsPlayerWidget_C", "SetPlannedSsProject");

	Params::WBP_UnitSsPlayerWidget_C_SetPlannedSsProject Parms{};

	Parms.InSsProject = InSsProject;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UnitSsPlayerWidget.WBP_UnitSsPlayerWidget_C.SetPlayFrame
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  InFrame                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UnitSsPlayerWidget_C::SetPlayFrame(double InFrame)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitSsPlayerWidget_C", "SetPlayFrame");

	Params::WBP_UnitSsPlayerWidget_C_SetPlayFrame Parms{};

	Parms.InFrame = InFrame;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UnitSsPlayerWidget.WBP_UnitSsPlayerWidget_C.SetUnitId
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const int32                             InId                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UnitSsPlayerWidget_C::SetUnitId(const int32 InId)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitSsPlayerWidget_C", "SetUnitId");

	Params::WBP_UnitSsPlayerWidget_C_SetUnitId Parms{};

	Parms.InId = InId;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UnitSsPlayerWidget.WBP_UnitSsPlayerWidget_C.StartInitialize
// (Private, BlueprintCallable, BlueprintEvent)

void UWBP_UnitSsPlayerWidget_C::StartInitialize()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitSsPlayerWidget_C", "StartInitialize");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UnitSsPlayerWidget.WBP_UnitSsPlayerWidget_C.GetNeutralAnimationData
// (Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// struct FMSP_AnimationData               ReturnValue                                            (Parm, OutParm, ReturnParm, NoDestructor)

struct FMSP_AnimationData UWBP_UnitSsPlayerWidget_C::GetNeutralAnimationData() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitSsPlayerWidget_C", "GetNeutralAnimationData");

	Params::WBP_UnitSsPlayerWidget_C_GetNeutralAnimationData Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_UnitSsPlayerWidget.WBP_UnitSsPlayerWidget_C.GetOneShotAnimationData
// (Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// struct FMSP_AnimationData               ReturnValue                                            (Parm, OutParm, ReturnParm, NoDestructor)

struct FMSP_AnimationData UWBP_UnitSsPlayerWidget_C::GetOneShotAnimationData() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitSsPlayerWidget_C", "GetOneShotAnimationData");

	Params::WBP_UnitSsPlayerWidget_C_GetOneShotAnimationData Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_UnitSsPlayerWidget.WBP_UnitSsPlayerWidget_C.GetUnitId
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

int32 UWBP_UnitSsPlayerWidget_C::GetUnitId() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitSsPlayerWidget_C", "GetUnitId");

	Params::WBP_UnitSsPlayerWidget_C_GetUnitId Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


SDK_NAMESPACE_END
