#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UnitEquippableItemEntry

#include "Basic.hpp"

#include "WBP_UnitEquippableItemEntry_classes.hpp"
#include "WBP_UnitEquippableItemEntry_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_UnitEquippableItemEntry.WBP_UnitEquippableItemEntry_C.ExecuteUbergraph_WBP_UnitEquippableItemEntry
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UnitEquippableItemEntry_C::ExecuteUbergraph_WBP_UnitEquippableItemEntry(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitEquippableItemEntry_C", "ExecuteUbergraph_WBP_UnitEquippableItemEntry");

	Params::WBP_UnitEquippableItemEntry_C_ExecuteUbergraph_WBP_UnitEquippableItemEntry Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UnitEquippableItemEntry.WBP_UnitEquippableItemEntry_C.OnInitialized
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_UnitEquippableItemEntry_C::OnInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitEquippableItemEntry_C", "OnInitialized");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UnitEquippableItemEntry.WBP_UnitEquippableItemEntry_C.SetIsEnable
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const bool                              InIs                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UnitEquippableItemEntry_C::SetIsEnable(const bool InIs)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitEquippableItemEntry_C", "SetIsEnable");

	Params::WBP_UnitEquippableItemEntry_C_SetIsEnable Parms{};

	Parms.InIs = InIs;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UnitEquippableItemEntry.WBP_UnitEquippableItemEntry_C.SetIsEquippedByOther
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    InIs                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UnitEquippableItemEntry_C::SetIsEquippedByOther(bool InIs)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitEquippableItemEntry_C", "SetIsEquippedByOther");

	Params::WBP_UnitEquippableItemEntry_C_SetIsEquippedByOther Parms{};

	Parms.InIs = InIs;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UnitEquippableItemEntry.WBP_UnitEquippableItemEntry_C.SetVM_UnitEquippableItem
// (Final, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UVM_UnitEquippableItem_C*         ViewModel                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_UnitEquippableItemEntry_C::SetVM_UnitEquippableItem(class UVM_UnitEquippableItem_C* ViewModel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitEquippableItemEntry_C", "SetVM_UnitEquippableItem");

	Params::WBP_UnitEquippableItemEntry_C_SetVM_UnitEquippableItem Parms{};

	Parms.ViewModel = ViewModel;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
