#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_FinishCmdTitle

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_FinishCmdTitle.WBP_FinishCmdTitle_C
// 0x0030 (0x0370 - 0x0340)
class UWBP_FinishCmdTitle_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0340(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWBP_TagKeyGuide_C*                     WBP_TagKeyGuide;                                   // 0x0348(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 IMG_addEffect;                                     // 0x0350(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_light;                                       // 0x0358(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_124;                                         // 0x0360(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetAnimation*                       A_Open;                                            // 0x0368(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)

public:
	void BindToCloseWidgetBegin(const TDelegate<void()>& InDelegate);
	void BindToCloseWidgetBeginByName(class UObject* InObject, const class FName InFuncName);
	void BindToCloseWidgetFinished(const TDelegate<void()>& InDelegate);
	void BindToCloseWidgetFinishedByName(class UObject* InObject, const class FName InFuncName);
	void BindToOpenWidgetFinished(const TDelegate<void()>& InDelegate);
	void BindToOpenWidgetFinishedByName(class UObject* InObject, const class FName InFuncName);
	void CloseWidget();
	void ExecuteUbergraph_WBP_FinishCmdTitle(int32 EntryPoint);
	void FinishCloseWidget();
	void FinishOpenWidget();
	void ForceCloseWidget();
	void OpenWidget();
	void PlayOpenAnimation();
	void ToggleOpenWidget();
	void UnbindToCloseWidgetBegin(const TDelegate<void()>& InDelegate);
	void UnbindToCloseWidgetBeginByName(class UObject* InObject, const class FName InFuncName);
	void UnbindToCloseWidgetFinished(const TDelegate<void()>& InDelegate);
	void UnbindToCloseWidgetFinishedByName(class UObject* InObject, const class FName InFuncName);
	void UnbindToOpenWidgetFinished(const TDelegate<void()>& InDelegate);
	void UnbindToOpenWidgetFinishedByName(class UObject* InObject, const class FName InFuncName);

	bool CanCloseWidget() const;
	bool CanOpenWidget() const;
	bool IsClosingProcess() const;
	bool IsOpenedWidget() const;
	bool IsOpeningProcess() const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_FinishCmdTitle_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_FinishCmdTitle_C")
	}
	static class UWBP_FinishCmdTitle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_FinishCmdTitle_C>();
	}
};
DUMPER7_ASSERTS_UWBP_FinishCmdTitle_C;

SDK_NAMESPACE_END
