#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_RecoveryIcon

#include "Basic.hpp"

#include "UMG_structs.hpp"
#include "UMG_classes.hpp"
#include "mucha_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_RecoveryIcon.WBP_RecoveryIcon_C
// 0x0008 (0x0348 - 0x0340)
class UWBP_RecoveryIcon_C final : public UUserWidget
{
public:
	class UImage*                                 Image_33;                                          // 0x0340(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void SetElementType(const EeElement InType);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_RecoveryIcon_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_RecoveryIcon_C")
	}
	static class UWBP_RecoveryIcon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_RecoveryIcon_C>();
	}
};
DUMPER7_ASSERTS_UWBP_RecoveryIcon_C;

SDK_NAMESPACE_END
