#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_FriendlyUnitHPGauge

#include "Basic.hpp"

#include "WBP_FriendlyUnitHPGauge_classes.hpp"
#include "WBP_FriendlyUnitHPGauge_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_FriendlyUnitHPGauge.WBP_FriendlyUnitHPGauge_C.AddPercent
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const float                             InAddPercent                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_FriendlyUnitHPGauge_C::AddPercent(const float InAddPercent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_FriendlyUnitHPGauge_C", "AddPercent");

	Params::WBP_FriendlyUnitHPGauge_C_AddPercent Parms{};

	Parms.InAddPercent = InAddPercent;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_FriendlyUnitHPGauge.WBP_FriendlyUnitHPGauge_C.SetHitPointPercent
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  InPercent                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_FriendlyUnitHPGauge_C::SetHitPointPercent(double InPercent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_FriendlyUnitHPGauge_C", "SetHitPointPercent");

	Params::WBP_FriendlyUnitHPGauge_C_SetHitPointPercent Parms{};

	Parms.InPercent = InPercent;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_FriendlyUnitHPGauge.WBP_FriendlyUnitHPGauge_C.SetPercent
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const float                             InPercent                                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_FriendlyUnitHPGauge_C::SetPercent(const float InPercent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_FriendlyUnitHPGauge_C", "SetPercent");

	Params::WBP_FriendlyUnitHPGauge_C_SetPercent Parms{};

	Parms.InPercent = InPercent;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_FriendlyUnitHPGauge.WBP_FriendlyUnitHPGauge_C.GetPercent
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

float UWBP_FriendlyUnitHPGauge_C::GetPercent() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_FriendlyUnitHPGauge_C", "GetPercent");

	Params::WBP_FriendlyUnitHPGauge_C_GetPercent Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


SDK_NAMESPACE_END
