#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UnitEquippedVision

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function WBP_UnitEquippedVision.WBP_UnitEquippedVision_C.SetViewModel
// 0x0018 (0x0018 - 0x0000)
struct WBP_UnitEquippedVision_C_SetViewModel final
{
public:
	class UMVVMViewModelBase*                     InVM;                                              // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UVM_UnitEquippedItemSlot_C*             K2Node_DynamicCast_AsVM_Unit_Equipped_Item_Slot;   // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_UnitEquippedVision_C_SetViewModel;

// Function WBP_UnitEquippedVision.WBP_UnitEquippedVision_C.SetVM_UnitEquippedItemSlot
// 0x0028 (0x0028 - 0x0000)
struct WBP_UnitEquippedVision_C_SetVM_UnitEquippedItemSlot final
{
public:
	class UVM_UnitEquippedItemSlot_C*             ViewModel;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UMVVMView*                              CallFunc_GetExtension_ReturnValue;                 // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class INotifyFieldValueChanged> CallFunc_SetViewModel_ViewModel_CastInput;      // 0x0010(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          CallFunc_SetViewModel_ReturnValue;                 // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_UnitEquippedVision_C_SetVM_UnitEquippedItemSlot;

// Function WBP_UnitEquippedVision.WBP_UnitEquippedVision_C.GetViewModel
// 0x0008 (0x0008 - 0x0000)
struct WBP_UnitEquippedVision_C_GetViewModel final
{
public:
	class UMVVMViewModelBase*                     ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_UnitEquippedVision_C_GetViewModel;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
