#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_BtlLibra_ConditionIcon

#include "Basic.hpp"

#include "mucha_structs.hpp"
#include "CoreUObject_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function WBP_BtlLibra_ConditionIcon.WBP_BtlLibra_ConditionIcon_C.ExecuteUbergraph_WBP_BtlLibra_ConditionIcon
// 0x0038 (0x0038 - 0x0000)
struct WBP_BtlLibra_ConditionIcon_C_ExecuteUbergraph_WBP_BtlLibra_ConditionIcon final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UCPP_WBP_GameplayTagBrush*              K2Node_CustomEvent_CPP_WBP_GameplayTagBrush_51;    // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           K2Node_CustomEvent_InColor;                        // 0x0010(0x0010)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class ICPP_BI_GameplayTagBrush> CallFunc_SetBrushColor_self_CastInput;          // 0x0028(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_BtlLibra_ConditionIcon_C_ExecuteUbergraph_WBP_BtlLibra_ConditionIcon;

// Function WBP_BtlLibra_ConditionIcon.WBP_BtlLibra_ConditionIcon_C.OnSetColor
// 0x0018 (0x0018 - 0x0000)
struct WBP_BtlLibra_ConditionIcon_C_OnSetColor final
{
public:
	class UCPP_WBP_GameplayTagBrush*              CPP_WBP_GameplayTagBrush_51;                       // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           InColor;                                           // 0x0008(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_BtlLibra_ConditionIcon_C_OnSetColor;

// Function WBP_BtlLibra_ConditionIcon.WBP_BtlLibra_ConditionIcon_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct WBP_BtlLibra_ConditionIcon_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_BtlLibra_ConditionIcon_C_PreConstruct;

// Function WBP_BtlLibra_ConditionIcon.WBP_BtlLibra_ConditionIcon_C.SetCondition
// 0x0018 (0x0018 - 0x0000)
struct WBP_BtlLibra_ConditionIcon_C_SetCondition final
{
public:
	EeUnitStatusCondition                         InType;                                            // 0x0000(0x0001)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class ICPP_BI_UI_UnitCondition> CallFunc_SetCondition_self_CastInput;           // 0x0008(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_BtlLibra_ConditionIcon_C_SetCondition;

// Function WBP_BtlLibra_ConditionIcon.WBP_BtlLibra_ConditionIcon_C.SetConditionList
// 0x0010 (0x0010 - 0x0000)
struct WBP_BtlLibra_ConditionIcon_C_SetConditionList final
{
public:
	TArray<EeUnitStatusCondition>                 InList;                                            // 0x0000(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
DUMPER7_ASSERTS_WBP_BtlLibra_ConditionIcon_C_SetConditionList;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
