#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_VisionStatus_Element

#include "Basic.hpp"

#include "UMG_structs.hpp"
#include "UMG_classes.hpp"
#include "mucha_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_VisionStatus_Element.WBP_VisionStatus_Element_C
// 0x0018 (0x0358 - 0x0340)
class UWBP_VisionStatus_Element_C final : public UUserWidget
{
public:
	class UWBP_RecoveryIcon_C*                    WBP_RecoveryIcon;                                  // 0x0340(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_ElementIconList_C*                 WBP_ElementIconList;                               // 0x0348(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCPP_VM_Vision*                         CPP_VM_Vision;                                     // 0x0350(0x0008)(BlueprintVisible, ZeroConstructor, Transient, DuplicateTransient, RepSkip, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)

public:
	void SetCPP_VM_Vision(class UCPP_VM_Vision* ViewModel);
	void SetElementList(const TArray<EeElement>& InList);
	void SetIsMasteryRecoverySkill(bool InIsMateryRecoverySkill);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_VisionStatus_Element_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_VisionStatus_Element_C")
	}
	static class UWBP_VisionStatus_Element_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_VisionStatus_Element_C>();
	}
};
DUMPER7_ASSERTS_UWBP_VisionStatus_Element_C;

SDK_NAMESPACE_END
