#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MouseCursor

#include "Basic.hpp"

#include "UMG_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function WBP_MouseCursor.WBP_MouseCursor_C.__70956639-4889-c65f-8f75-80bbfda1bfdb_SourceToDest
// 0x0002 (0x0002 - 0x0000)
struct WBP_MouseCursor_C___70956639_4889_c65f_8f75_80bbfda1bfdb_SourceToDest final
{
public:
	ESlateVisibility                              ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              CallFunc_Conv_BoolToSlateVisibility_ReturnValue;   // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_MouseCursor_C___70956639_4889_c65f_8f75_80bbfda1bfdb_SourceToDest;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
