#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ItemNum

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Slate_structs.hpp"
#include "UMG_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_ItemNum.WBP_ItemNum_C
// 0x0028 (0x0368 - 0x0340)
class UWBP_ItemNum_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0340(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UCommonTextBlock*                       Text_Num;                                          // 0x0348(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FText                                   TextFormat;                                        // 0x0350(0x0010)(Edit, BlueprintVisible)
	int32                                         Num;                                               // 0x0360(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETextJustify                                  TextJustification;                                 // 0x0364(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_ItemNum(int32 EntryPoint);
	void PreConstruct(bool IsDesignTime);
	void SetNum(int32 InNum);
	void SetTextFormat(class FText& InTextFormat);
	void SetTextJustification(ETextJustify InTextJustification);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_ItemNum_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_ItemNum_C")
	}
	static class UWBP_ItemNum_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_ItemNum_C>();
	}
};
DUMPER7_ASSERTS_UWBP_ItemNum_C;

SDK_NAMESPACE_END
