#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_BtlCmd_SkillEntry

#include "Basic.hpp"

#include "WBP_BtlCmdEntryBase_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_BtlCmd_SkillEntry.WBP_BtlCmd_SkillEntry_C
// 0x0010 (0x04D0 - 0x04C0)
class UWBP_BtlCmd_SkillEntry_C final : public UWBP_BtlCmdEntryBase_C
{
public:
	class UWBP_SkillCost_C*                       WBP_SkillCost;                                     // 0x04C0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVM_BtlCmd_C*                           VM_BtlCmd;                                         // 0x04C8(0x0008)(BlueprintVisible, ZeroConstructor, Transient, DuplicateTransient, RepSkip, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)

public:
	void SetActionKey(const struct FActionKey& InKey);
	void SetBtlCmdVM(class UVM_BtlCmd_C* InBtlCmdVM);
	void SetUnitId(int32 InId);
	void SetVM_BtlCmd(class UVM_BtlCmd_C* ViewModel);

	struct FActionKey GetActionKey() const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_BtlCmd_SkillEntry_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_BtlCmd_SkillEntry_C")
	}
	static class UWBP_BtlCmd_SkillEntry_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_BtlCmd_SkillEntry_C>();
	}
};
DUMPER7_ASSERTS_UWBP_BtlCmd_SkillEntry_C;

SDK_NAMESPACE_END
