#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PrimartButton_Frame

#include "Basic.hpp"

#include "UMG_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_PrimartButton_Frame.WBP_PrimartButton_Frame_C
// 0x0000 (0x0340 - 0x0340)
class UWBP_PrimartButton_Frame_C final : public UUserWidget
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_PrimartButton_Frame_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_PrimartButton_Frame_C")
	}
	static class UWBP_PrimartButton_Frame_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_PrimartButton_Frame_C>();
	}
};
DUMPER7_ASSERTS_UWBP_PrimartButton_Frame_C;

SDK_NAMESPACE_END
