#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UnitStatus_RollEntry

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function WBP_UnitStatus_RollEntry.WBP_UnitStatus_RollEntry_C.SetText
// 0x0010 (0x0010 - 0x0000)
struct WBP_UnitStatus_RollEntry_C_SetText final
{
public:
	class FText                                   InText;                                            // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm)
};
DUMPER7_ASSERTS_WBP_UnitStatus_RollEntry_C_SetText;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
