#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_VisionUpGradeCost

#include "Basic.hpp"

#include "WBP_VisionUpGradeCost_classes.hpp"
#include "WBP_VisionUpGradeCost_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_VisionUpGradeCost.WBP_VisionUpGradeCost_C.Destruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_VisionUpGradeCost_C::Destruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_VisionUpGradeCost_C", "Destruct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_VisionUpGradeCost.WBP_VisionUpGradeCost_C.ExecuteUbergraph_WBP_VisionUpGradeCost
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_VisionUpGradeCost_C::ExecuteUbergraph_WBP_VisionUpGradeCost(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_VisionUpGradeCost_C", "ExecuteUbergraph_WBP_VisionUpGradeCost");

	Params::WBP_VisionUpGradeCost_C_ExecuteUbergraph_WBP_VisionUpGradeCost Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_VisionUpGradeCost.WBP_VisionUpGradeCost_C.HandleUseUpGradeItem
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UCPP_MuchaDelegateValue*          pValue                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_VisionUpGradeCost_C::HandleUseUpGradeItem(class UCPP_MuchaDelegateValue* pValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_VisionUpGradeCost_C", "HandleUseUpGradeItem");

	Params::WBP_VisionUpGradeCost_C_HandleUseUpGradeItem Parms{};

	Parms.pValue = pValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_VisionUpGradeCost.WBP_VisionUpGradeCost_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_VisionUpGradeCost_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_VisionUpGradeCost_C", "PreConstruct");

	Params::WBP_VisionUpGradeCost_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_VisionUpGradeCost.WBP_VisionUpGradeCost_C.SetColor
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const int32                             InItemId                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_VisionUpGradeCost_C::SetColor(const int32 InItemId)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_VisionUpGradeCost_C", "SetColor");

	Params::WBP_VisionUpGradeCost_C_SetColor Parms{};

	Parms.InItemId = InItemId;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_VisionUpGradeCost.WBP_VisionUpGradeCost_C.SetCPP_VM_Vision
// (Final, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UCPP_VM_Vision*                   ViewModel                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_VisionUpGradeCost_C::SetCPP_VM_Vision(class UCPP_VM_Vision* ViewModel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_VisionUpGradeCost_C", "SetCPP_VM_Vision");

	Params::WBP_VisionUpGradeCost_C_SetCPP_VM_Vision Parms{};

	Parms.ViewModel = ViewModel;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_VisionUpGradeCost.WBP_VisionUpGradeCost_C.SetVisionId
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   InVisionId                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_VisionUpGradeCost_C::SetVisionId(int32 InVisionId)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_VisionUpGradeCost_C", "SetVisionId");

	Params::WBP_VisionUpGradeCost_C_SetVisionId Parms{};

	Parms.InVisionId = InVisionId;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_VisionUpGradeCost.WBP_VisionUpGradeCost_C.SyncUpGradeCost
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_VisionUpGradeCost_C::SyncUpGradeCost()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_VisionUpGradeCost_C", "SyncUpGradeCost");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
