#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_EquipDetail

#include "Basic.hpp"

#include "mucha_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function WBP_EquipDetail.WBP_EquipDetail_C.SetEquipData
// 0x0148 (0x0148 - 0x0000)
struct WBP_EquipDetail_C_SetEquipData final
{
public:
	struct FEQUIPMENT_ITEM_DATA                   InData;                                            // 0x0000(0x00E8)(BlueprintVisible, BlueprintReadOnly, Parm)
	TMap<EeUnitParameterType, int32>              CallFunc_SortParamList_OutSortParamList;           // 0x00E8(0x0050)()
	class FText                                   CallFunc_NormalizeLineBreaks_Text_ReturnValue;     // 0x0138(0x0010)()
};
DUMPER7_ASSERTS_WBP_EquipDetail_C_SetEquipData;

// Function WBP_EquipDetail.WBP_EquipDetail_C.SortParamList
// 0x0198 (0x0198 - 0x0000)
struct WBP_EquipDetail_C_SortParamList final
{
public:
	TMap<EeUnitParameterType, int32>              InParamList;                                       // 0x0000(0x0050)(BlueprintVisible, BlueprintReadOnly, Parm)
	TMap<EeUnitParameterType, int32>              OutSortParamList;                                  // 0x0050(0x0050)(Parm, OutParm)
	TMap<EeUnitParameterType, int32>              l_SortParamList;                                   // 0x00A0(0x0050)(Edit, BlueprintVisible)
	TArray<EeUnitParameterType>                   l_ExceptParamList;                                 // 0x00F0(0x0010)(Edit, BlueprintVisible)
	TArray<EeUnitParameterType>                   K2Node_MakeArray_Array;                            // 0x0100(0x0010)(ReferenceParm)
	TArray<EeUnitParameterType>                   CallFunc_Map_Keys_Keys;                            // 0x0110(0x0010)(ReferenceParm)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0120(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0124(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0128(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EeUnitParameterType                           CallFunc_Array_Get_Item;                           // 0x012C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x012D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_12E[0x2];                                      // 0x012E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0130(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_134[0x4];                                      // 0x0134(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TMap<EeUnitParameterType, int32>              K2Node_MakeVariable_MakeVariableOutput;            // 0x0138(0x0050)()
	int32                                         CallFunc_Array_Find_ReturnValue;                   // 0x0188(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Comp_Int32_Equal_Minus1_ReturnValue;      // 0x018C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_18D[0x3];                                      // 0x018D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Map_Find_Value;                           // 0x0190(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue;                     // 0x0194(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_EquipDetail_C_SortParamList;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
