#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PredictProgress

#include "Basic.hpp"

#include "mucha_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_PredictProgress.WBP_PredictProgress_C
// 0x0000 (0x03E8 - 0x03E8)
class UWBP_PredictProgress_C final : public UCPP_WBP_PredictProgress
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_PredictProgress_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_PredictProgress_C")
	}
	static class UWBP_PredictProgress_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_PredictProgress_C>();
	}
};
DUMPER7_ASSERTS_UWBP_PredictProgress_C;

SDK_NAMESPACE_END
