#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UnitEquippableSkillEntry

#include "Basic.hpp"

#include "WBP_UnitEquippableSkillEntry_classes.hpp"
#include "WBP_UnitEquippableSkillEntry_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_UnitEquippableSkillEntry.WBP_UnitEquippableSkillEntry_C.ExecuteUbergraph_WBP_UnitEquippableSkillEntry
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UnitEquippableSkillEntry_C::ExecuteUbergraph_WBP_UnitEquippableSkillEntry(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitEquippableSkillEntry_C", "ExecuteUbergraph_WBP_UnitEquippableSkillEntry");

	Params::WBP_UnitEquippableSkillEntry_C_ExecuteUbergraph_WBP_UnitEquippableSkillEntry Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UnitEquippableSkillEntry.WBP_UnitEquippableSkillEntry_C.OnInitialized
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_UnitEquippableSkillEntry_C::OnInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitEquippableSkillEntry_C", "OnInitialized");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UnitEquippableSkillEntry.WBP_UnitEquippableSkillEntry_C.SetIsDisplayOwner
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    InIs                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UnitEquippableSkillEntry_C::SetIsDisplayOwner(bool InIs)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitEquippableSkillEntry_C", "SetIsDisplayOwner");

	Params::WBP_UnitEquippableSkillEntry_C_SetIsDisplayOwner Parms{};

	Parms.InIs = InIs;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UnitEquippableSkillEntry.WBP_UnitEquippableSkillEntry_C.SetIsEnable
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    InIs                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UnitEquippableSkillEntry_C::SetIsEnable(bool InIs)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitEquippableSkillEntry_C", "SetIsEnable");

	Params::WBP_UnitEquippableSkillEntry_C_SetIsEnable Parms{};

	Parms.InIs = InIs;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UnitEquippableSkillEntry.WBP_UnitEquippableSkillEntry_C.SetIsMaster
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    InIs                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UnitEquippableSkillEntry_C::SetIsMaster(bool InIs)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitEquippableSkillEntry_C", "SetIsMaster");

	Params::WBP_UnitEquippableSkillEntry_C_SetIsMaster Parms{};

	Parms.InIs = InIs;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UnitEquippableSkillEntry.WBP_UnitEquippableSkillEntry_C.SetIsSelectable
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const bool                              InIs                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UnitEquippableSkillEntry_C::SetIsSelectable(const bool InIs)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitEquippableSkillEntry_C", "SetIsSelectable");

	Params::WBP_UnitEquippableSkillEntry_C_SetIsSelectable Parms{};

	Parms.InIs = InIs;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UnitEquippableSkillEntry.WBP_UnitEquippableSkillEntry_C.SetVM_UnitEquippableSkill
// (Final, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UVM_UnitEquippableSkill_C*        ViewModel                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_UnitEquippableSkillEntry_C::SetVM_UnitEquippableSkill(class UVM_UnitEquippableSkill_C* ViewModel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitEquippableSkillEntry_C", "SetVM_UnitEquippableSkill");

	Params::WBP_UnitEquippableSkillEntry_C_SetVM_UnitEquippableSkill Parms{};

	Parms.ViewModel = ViewModel;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UnitEquippableSkillEntry.WBP_UnitEquippableSkillEntry_C.SyncButtonStyle
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_UnitEquippableSkillEntry_C::SyncButtonStyle()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitEquippableSkillEntry_C", "SyncButtonStyle");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
