#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_FinishCmdMenu

#include "Basic.hpp"

#include "mucha_structs.hpp"
#include "EnhancedUI_structs.hpp"
#include "EnhancedUI_classes.hpp"
#include "SlateCore_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_FinishCmdMenu.WBP_FinishCmdMenu_C
// 0x0030 (0x0508 - 0x04D8)
class UWBP_FinishCmdMenu_C final : public UCPP_WBP_MenuBase
{
public:
	class URetainerBox*                           RetainerBox_0;                                     // 0x04D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               Overlay_Key;                                       // 0x04E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               Overlay_Entry;                                     // 0x04E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetAnimation*                       A_Open;                                            // 0x04F0(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	TArray<struct FFinishCmdEntryData>            EntryDataList;                                     // 0x04F8(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void AddEntryToOverlay(class UOverlay* InOverlay, class UWidget* InWidget, const struct FFinishCmdEntryData& InEntryData);
	void BindToCloseWidgetBegin(const TDelegate<void()>& InDelegate);
	void BindToCloseWidgetBeginByName(class UObject* InObject, const class FName InFuncName);
	void BindToCloseWidgetFinished(const TDelegate<void()>& InDelegate);
	void BindToCloseWidgetFinishedByName(class UObject* InObject, const class FName InFuncName);
	void BindToOpenWidgetFinished(const TDelegate<void()>& InDelegate);
	void BindToOpenWidgetFinishedByName(class UObject* InObject, const class FName InFuncName);
	void CloseWidget();
	void CreateEntry(const struct FFinishCmdEntryData& InEntryData);
	void CreateKey(const struct FFinishCmdEntryData& InEntryData);
	void FinishCloseWidget();
	void FinishOpenWidget();
	void ForceCloseWidget();
	void InputDirection(const EUINavigation InNavigation, const EWidgetInputEventType InEventType);
	void OpenWidget();
	void SetEntryDataList(TArray<struct FFinishCmdEntryData>& InList);
	void ToggleOpenWidget();
	void UnbindToCloseWidgetBegin(const TDelegate<void()>& InDelegate);
	void UnbindToCloseWidgetBeginByName(class UObject* InObject, const class FName InFuncName);
	void UnbindToCloseWidgetFinished(const TDelegate<void()>& InDelegate);
	void UnbindToCloseWidgetFinishedByName(class UObject* InObject, const class FName InFuncName);
	void UnbindToOpenWidgetFinished(const TDelegate<void()>& InDelegate);
	void UnbindToOpenWidgetFinishedByName(class UObject* InObject, const class FName InFuncName);

	bool CanCloseWidget() const;
	bool CanOpenWidget() const;
	bool IsClosingProcess() const;
	bool IsOpenedWidget() const;
	bool IsOpeningProcess() const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_FinishCmdMenu_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_FinishCmdMenu_C")
	}
	static class UWBP_FinishCmdMenu_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_FinishCmdMenu_C>();
	}
};
DUMPER7_ASSERTS_UWBP_FinishCmdMenu_C;

SDK_NAMESPACE_END
