#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_DesignButton

#include "Basic.hpp"

#include "EnhancedUI_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_DesignButton.WBP_DesignButton_C
// 0x0010 (0x04C0 - 0x04B0)
class UWBP_DesignButton_C final : public UCPP_WBP_ButtonPath
{
public:
	class UWBP_ButtonBase_C*                      WBP_ButtonBase;                                    // 0x04B0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       CommonTextBlock_71;                                // 0x04B8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void SetEntryIndex(int32 InIndex, int32* Return);

	void GetEntryIndex(int32* Return) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_DesignButton_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_DesignButton_C")
	}
	static class UWBP_DesignButton_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_DesignButton_C>();
	}
};
DUMPER7_ASSERTS_UWBP_DesignButton_C;

SDK_NAMESPACE_END
