#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_BtlCmd_ListFrame

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "mucha_structs.hpp"
#include "mucha_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_BtlCmd_ListFrame.WBP_BtlCmd_ListFrame_C
// 0x00D0 (0x0630 - 0x0560)
class UWBP_BtlCmd_ListFrame_C final : public UCPP_WBP_BtlCmd_FlowStepBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0560(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWBP_BtlCmd_SecondaryList_C*            WBP_BtlCmd_SecondaryList;                          // 0x0568(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_BtlCmd_PrimaryList_C*              WBP_BtlCmd_PrimaryList;                            // 0x0570(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetAnimation*                       A_Open;                                            // 0x0578(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       A_Close;                                           // 0x0580(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       A_ListChanged;                                     // 0x0588(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UVM_BtlCmd_C*                           VM_BtlCmd;                                         // 0x0590(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, DisableEditOnInstance, DuplicateTransient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UCPP_VM_BtlCmdUnitSelect*               CPP_VM_BtlCmdUnitSelect;                           // 0x0598(0x0008)(BlueprintVisible, ZeroConstructor, Transient, DuplicateTransient, RepSkip, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	struct FBtlCmd_EntryValue                     CalledCmdValue;                                    // 0x05A0(0x0048)(Edit, BlueprintVisible, DisableEditOnInstance)
	class UCPP_DA_BtlCmdBehavior*                 BehaviorDA;                                        // 0x05E8(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FBtlCmdBehavior                        BtlCmdBehavior;                                    // 0x05F0(0x0040)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void BP_OnActivated();
	void BP_OnDeactivated();
	void ExecuteCmdListState(bool IsBegin);
	void ExecuteUbergraph_WBP_BtlCmd_ListFrame(int32 EntryPoint);
	class UClass* GetBehaviorWidget(const struct FBtlCmdBehavior& InBehavior);
	void HandleEntryEvent(const struct FButtonEventTriggeredData& InTriggeredData);
	void HandleFocusedEntry(const struct FButtonEventTriggeredData& InTriggeredData);
	void OnRequestOpen();
	void ReflectStyle();
	void Set_Unit_Select_VM(class UCPP_VM_BtlCmdUnitSelect* ViewModel);
	void SetBtlCmdBehavior(const struct FBtlCmd_EntryBehavior& InData);
	void SetBtlCmdValue(const struct FBtlCmd_Value& InValue);
	void SetCPP_VM_BtlCmdUnitSelect(class UCPP_VM_BtlCmdUnitSelect* ViewModel);
	void SetSceneData(const struct FBtlCmdSceneData& InData);
	void WidgetAnimationEvt_A_Close_K2Node_WidgetAnimationEvent_2();
	void WidgetAnimationEvt_A_Open_K2Node_WidgetAnimationEvent_0();

	struct FBtlCmd_EntryValue GetCmdEntryValue() const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_BtlCmd_ListFrame_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_BtlCmd_ListFrame_C")
	}
	static class UWBP_BtlCmd_ListFrame_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_BtlCmd_ListFrame_C>();
	}
};
DUMPER7_ASSERTS_UWBP_BtlCmd_ListFrame_C;

SDK_NAMESPACE_END
