#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_BtlCmd_ListHeader

#include "Basic.hpp"

#include "UMG_structs.hpp"
#include "UMG_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_BtlCmd_ListHeader.WBP_BtlCmd_ListHeader_C
// 0x0048 (0x0388 - 0x0340)
class UWBP_BtlCmd_ListHeader_C final : public UUserWidget
{
public:
	class UWBP_TagKeyGuide_C*                     WBP_TagKeyGuide;                                   // 0x0340(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_BtlCmd_ListUnit_C*                 WBP_BtlCmd_ListUnit;                               // 0x0348(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               Overlay_Limit;                                     // 0x0350(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_LimitEffect_line;                            // 0x0358(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_LimitEffect_Glow;                            // 0x0360(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_LimitEffect;                                 // 0x0368(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCPP_WBP_HorizontalGradient*            CPP_WBP_HorizontalGradient_125;                    // 0x0370(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVM_BtlCmd_C*                           VM_BtlCmd;                                         // 0x0378(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, DisableEditOnInstance, DuplicateTransient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UCPP_VM_BtlUnitParam*                   CPP_VM_BtlUnitParam;                               // 0x0380(0x0008)(BlueprintVisible, ZeroConstructor, Transient, DuplicateTransient, RepSkip, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)

public:
	void SetCPP_VM_BtlUnitParam(class UCPP_VM_BtlUnitParam* ViewModel);
	void SetHasLimit(bool InIs);
	void SetUniqueId(int32 InId);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_BtlCmd_ListHeader_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_BtlCmd_ListHeader_C")
	}
	static class UWBP_BtlCmd_ListHeader_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_BtlCmd_ListHeader_C>();
	}
};
DUMPER7_ASSERTS_UWBP_BtlCmd_ListHeader_C;

SDK_NAMESPACE_END
