#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Collossseum_CommandEntry

#include "Basic.hpp"

#include "WBP_Collossseum_CommandEntry_classes.hpp"
#include "WBP_Collossseum_CommandEntry_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_Collossseum_CommandEntry.WBP_Collossseum_CommandEntry_C.BP_OnClicked
// (Event, Protected, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FButtonEventTriggeredData& InTriggeredData                                        (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, ContainsInstancedReference)

void UWBP_Collossseum_CommandEntry_C::BP_OnClicked(const struct FButtonEventTriggeredData& InTriggeredData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Collossseum_CommandEntry_C", "BP_OnClicked");

	Params::WBP_Collossseum_CommandEntry_C_BP_OnClicked Parms{};

	Parms.InTriggeredData = std::move(InTriggeredData);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Collossseum_CommandEntry.WBP_Collossseum_CommandEntry_C.BP_OnFocused
// (Event, Protected, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FButtonEventTriggeredData& InTriggeredData                                        (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, ContainsInstancedReference)

void UWBP_Collossseum_CommandEntry_C::BP_OnFocused(const struct FButtonEventTriggeredData& InTriggeredData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Collossseum_CommandEntry_C", "BP_OnFocused");

	Params::WBP_Collossseum_CommandEntry_C_BP_OnFocused Parms{};

	Parms.InTriggeredData = std::move(InTriggeredData);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Collossseum_CommandEntry.WBP_Collossseum_CommandEntry_C.ExecuteUbergraph_WBP_Collossseum_CommandEntry
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Collossseum_CommandEntry_C::ExecuteUbergraph_WBP_Collossseum_CommandEntry(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Collossseum_CommandEntry_C", "ExecuteUbergraph_WBP_Collossseum_CommandEntry");

	Params::WBP_Collossseum_CommandEntry_C_ExecuteUbergraph_WBP_Collossseum_CommandEntry Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Collossseum_CommandEntry.WBP_Collossseum_CommandEntry_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Collossseum_CommandEntry_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Collossseum_CommandEntry_C", "PreConstruct");

	Params::WBP_Collossseum_CommandEntry_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Collossseum_CommandEntry.WBP_Collossseum_CommandEntry_C.SetLevel
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_Collossseum_CommandEntry_C::SetLevel()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Collossseum_CommandEntry_C", "SetLevel");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Collossseum_CommandEntry.WBP_Collossseum_CommandEntry_C.SetOptionMenuEntryInfo
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FOP_BaseMenu_EntryInfo&    InInfo                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm)

void UWBP_Collossseum_CommandEntry_C::SetOptionMenuEntryInfo(const struct FOP_BaseMenu_EntryInfo& InInfo)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Collossseum_CommandEntry_C", "SetOptionMenuEntryInfo");

	Params::WBP_Collossseum_CommandEntry_C_SetOptionMenuEntryInfo Parms{};

	Parms.InInfo = std::move(InInfo);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Collossseum_CommandEntry.WBP_Collossseum_CommandEntry_C.GetOptionEntryInfo
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// struct FOP_BaseMenu_EntryInfo           ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FOP_BaseMenu_EntryInfo UWBP_Collossseum_CommandEntry_C::GetOptionEntryInfo() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Collossseum_CommandEntry_C", "GetOptionEntryInfo");

	Params::WBP_Collossseum_CommandEntry_C_GetOptionEntryInfo Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


SDK_NAMESPACE_END
