#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UnitDataEntry

#include "Basic.hpp"

#include "WBP_UnitDataEntry_classes.hpp"
#include "WBP_UnitDataEntry_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_UnitDataEntry.WBP_UnitDataEntry_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_UnitDataEntry_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitDataEntry_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UnitDataEntry.WBP_UnitDataEntry_C.Destruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_UnitDataEntry_C::Destruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitDataEntry_C", "Destruct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UnitDataEntry.WBP_UnitDataEntry_C.ExecuteUbergraph_WBP_UnitDataEntry
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UnitDataEntry_C::ExecuteUbergraph_WBP_UnitDataEntry(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitDataEntry_C", "ExecuteUbergraph_WBP_UnitDataEntry");

	Params::WBP_UnitDataEntry_C_ExecuteUbergraph_WBP_UnitDataEntry Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UnitDataEntry.WBP_UnitDataEntry_C.PlaySkillEffect
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FUISkillActionData&        InKey                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void UWBP_UnitDataEntry_C::PlaySkillEffect(const struct FUISkillActionData& InKey)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitDataEntry_C", "PlaySkillEffect");

	Params::WBP_UnitDataEntry_C_PlaySkillEffect Parms{};

	Parms.InKey = std::move(InKey);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UnitDataEntry.WBP_UnitDataEntry_C.PlayUnitSkillEffect
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   SkillId                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UnitDataEntry_C::PlayUnitSkillEffect(int32 SkillId)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitDataEntry_C", "PlayUnitSkillEffect");

	Params::WBP_UnitDataEntry_C_PlayUnitSkillEffect Parms{};

	Parms.SkillId = SkillId;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UnitDataEntry.WBP_UnitDataEntry_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UnitDataEntry_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitDataEntry_C", "PreConstruct");

	Params::WBP_UnitDataEntry_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UnitDataEntry.WBP_UnitDataEntry_C.SetCPP_VM_UnitParam
// (Final, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UCPP_VM_UnitParam*                ViewModel                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_UnitDataEntry_C::SetCPP_VM_UnitParam(class UCPP_VM_UnitParam* ViewModel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitDataEntry_C", "SetCPP_VM_UnitParam");

	Params::WBP_UnitDataEntry_C_SetCPP_VM_UnitParam Parms{};

	Parms.ViewModel = ViewModel;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UnitDataEntry.WBP_UnitDataEntry_C.SetForceVisibleCursor
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsForce                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UnitDataEntry_C::SetForceVisibleCursor(bool IsForce)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitDataEntry_C", "SetForceVisibleCursor");

	Params::WBP_UnitDataEntry_C_SetForceVisibleCursor Parms{};

	Parms.IsForce = IsForce;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UnitDataEntry.WBP_UnitDataEntry_C.SetIsWidgetEnabled
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const bool                              InIsEnabled                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UnitDataEntry_C::SetIsWidgetEnabled(const bool InIsEnabled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitDataEntry_C", "SetIsWidgetEnabled");

	Params::WBP_UnitDataEntry_C_SetIsWidgetEnabled Parms{};

	Parms.InIsEnabled = InIsEnabled;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UnitDataEntry.WBP_UnitDataEntry_C.SetSkillActionData
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FUISkillActionData&        InKey                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)

void UWBP_UnitDataEntry_C::SetSkillActionData(const struct FUISkillActionData& InKey)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitDataEntry_C", "SetSkillActionData");

	Params::WBP_UnitDataEntry_C_SetSkillActionData Parms{};

	Parms.InKey = std::move(InKey);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UnitDataEntry.WBP_UnitDataEntry_C.SetUnitId
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const int32                             InId                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UnitDataEntry_C::SetUnitId(const int32 InId)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitDataEntry_C", "SetUnitId");

	Params::WBP_UnitDataEntry_C_SetUnitId Parms{};

	Parms.InId = InId;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UnitDataEntry.WBP_UnitDataEntry_C.SetVM
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class UMVVMViewModelBase*         InViewModel                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_UnitDataEntry_C::SetVM(const class UMVVMViewModelBase* InViewModel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitDataEntry_C", "SetVM");

	Params::WBP_UnitDataEntry_C_SetVM Parms{};

	Parms.InViewModel = InViewModel;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UnitDataEntry.WBP_UnitDataEntry_C.UpdateEquipVision
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_UnitDataEntry_C::UpdateEquipVision()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitDataEntry_C", "UpdateEquipVision");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UnitDataEntry.WBP_UnitDataEntry_C.WBP_UnitDataEntry_AutoGenFunc
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UCPP_MuchaDelegateValue*          pValue                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_UnitDataEntry_C::WBP_UnitDataEntry_AutoGenFunc(class UCPP_MuchaDelegateValue* pValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitDataEntry_C", "WBP_UnitDataEntry_AutoGenFunc");

	Params::WBP_UnitDataEntry_C_WBP_UnitDataEntry_AutoGenFunc Parms{};

	Parms.pValue = pValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UnitDataEntry.WBP_UnitDataEntry_C.GetSkillActionData
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// struct FUISkillActionData               ReturnValue                                            (Parm, OutParm, ReturnParm, NoDestructor)

struct FUISkillActionData UWBP_UnitDataEntry_C::GetSkillActionData() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitDataEntry_C", "GetSkillActionData");

	Params::WBP_UnitDataEntry_C_GetSkillActionData Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_UnitDataEntry.WBP_UnitDataEntry_C.GetUnitId
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

int32 UWBP_UnitDataEntry_C::GetUnitId() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UnitDataEntry_C", "GetUnitId");

	Params::WBP_UnitDataEntry_C_GetUnitId Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


SDK_NAMESPACE_END
