#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_BtlCmd_PrimaryList

#include "Basic.hpp"

#include "UMG_structs.hpp"
#include "CoreUObject_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function WBP_BtlCmd_PrimaryList.WBP_BtlCmd_PrimaryList_C.ExecuteUbergraph_WBP_BtlCmd_PrimaryList
// 0x0004 (0x0004 - 0x0000)
struct WBP_BtlCmd_PrimaryList_C_ExecuteUbergraph_WBP_BtlCmd_PrimaryList final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_BtlCmd_PrimaryList_C_ExecuteUbergraph_WBP_BtlCmd_PrimaryList;

// Function WBP_BtlCmd_PrimaryList.WBP_BtlCmd_PrimaryList_C.SetIsTarget
// 0x0014 (0x0014 - 0x0000)
struct WBP_BtlCmd_PrimaryList_C_SetIsTarget final
{
public:
	bool                                          InIs;                                              // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              CallFunc_Cast_SlateVisibility_From_Bool_ReturnValue; // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              CallFunc_Cast_SlateVisibility_From_Bool_ReturnValue_1; // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3[0x1];                                        // 0x0003(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           CallFunc_SelectColor_ReturnValue;                  // 0x0004(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_BtlCmd_PrimaryList_C_SetIsTarget;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
